- .vscode/launch.json
Adds VSCode launch configuration for Firefox.
> [DEV] Launch configuration for Firefox debugging

- pandora-client-web/src/components/chatroom/chatroom.tsx
- pandora-client-web/src/components/header/Header.tsx
- pandora-client-web/src/components/header/leaveButton.scss
- pandora-client-web/src/components/header/leaveButton.tsx
> [CHANGE] unify leave actions to the top right button

- pandora-client-web/src/common/useMediaQuery.ts
- pandora-client-web/src/components/chatroom/chat.tsx
- pandora-client-web/src/components/chatroom/chatRoomScene.tsx
- pandora-client-web/src/components/chatroom/chatroom.scss
- pandora-client-web/src/components/chatroom/chatroom.tsx
- pandora-client-web/src/components/chatroom/chatroomControls.tsx
- pandora-client-web/src/components/gameContext/chatRoomContextProvider.tsx
- pandora-client-web/src/components/gameContext/directoryConnectorContextProvider.tsx
- pandora-client-web/src/components/gameContext/playerContextProvider.tsx
- pandora-client-web/src/components/header/Header.tsx
- pandora-client-web/src/components/header/leaveButton.tsx
- pandora-client-web/src/components/settings/interfaceSettings.tsx
- pandora-client-web/src/networking/socketio_directory_connector.ts
- pandora-client-web/src/styles/mediaQueries.ts
- pandora-common/src/networking/directory_client.ts
This PR refactors chatroom, splitting the code more, reusing more common components and cleaning up the looks a bit.
It also introduces new feature: Ability to configure ratio of graphics to chat, defaulting to 7:3 (4:6 for portrait).
Also disables the test popup that has no value and somehow made it in through the review, I will yet look for how it got in without being rejected.
> [CHANGE] Chatroom rework

- pandora-client-web/src/components/chatroom/chatInput.tsx
- pandora-client-web/src/components/chatroom/chatroom.tsx
Fixes regression introduced by #301 and modifies the context to more easily catch this problem in the future.
> [FIX] Fix broken chat input mode selection

- pandora-server-directory/package.json
- pandora-server-directory/src/config.ts
- pandora-server-directory/src/services/email/baseEmail.ts
- pandora-server-directory/src/services/email/index.ts
- pandora-server-directory/src/services/email/mockEmail.ts
- pandora-server-directory/src/services/email/sesEmail.ts
- pandora-server-directory/src/services/email/smtpEmail.ts
- pnpm-lock.yaml
Our current free SMTP provider become unreliable so we need to move to a new service.
I put on-hold on this PR until AWS approved my production access request and I successfully use the service
> [ADD] AWS SES email transport handling

- pandora-client-web/src/components/characterSafemode/characterSafemode.tsx
- pandora-client-web/src/components/chatroom/chatroom.scss
- pandora-client-web/src/components/chatroom/chatroom.tsx
- pandora-client-web/src/components/chatroom/chatroomControls.tsx
- pandora-client-web/src/components/chatroomSelect/chatroomSelect.tsx
- pandora-client-web/src/components/gameContext/chatRoomContextProvider.tsx
- pandora-client-web/src/components/settings/settings.scss
- pandora-client-web/src/components/wiki/pages/intro.tsx
Redesigns the "Room" tab of room controls:
> [CHANGE] Room tab redesign

- pandora-client-web/src/character/character.ts
- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
- pandora-client-web/src/components/chatroom/chatRoomScene.tsx
- pandora-client-web/src/components/settings/interfaceSettings.tsx
- pandora-client-web/src/components/wardrobe/wardrobe.tsx
- pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
- pandora-client-web/src/components/wardrobe/wardrobeTypes.ts
- pandora-client-web/src/editor/editor.tsx
- pandora-client-web/src/editor/graphics/character/appearanceEditor.ts
- pandora-client-web/src/editor/graphics/editorScene.tsx
- pandora-client-web/src/graphics/graphicsScene.tsx
- pandora-client-web/src/graphics/useTexture.ts
- pandora-common/src/networking/directory_client.ts
The main purpose of this PR is to show room background inside chatroom, in same scale and offset to the target character as is visible in the room. Note, that it currently ignores room device position overrides.
Commits should be atomic and self-contained.
> [FEATURE] Show room background inside chatroom

- pandora-client-web/src/editor/parsing.ts
- pandora-client-web/src/graphics/appearanceConditionEvaluator.ts
- pandora-client-web/src/graphics/mirroring.ts
- pandora-client-web/src/graphics/utility.ts
- pandora-common/src/assets/graphics/graphics.ts
allow an attribute to be required or not allowed if it is prefixed with `!`
resolves #268
> [FEATURE] attributes as atomic conditions

- pandora-client-web/src/components/hoverElement/hoverElement.tsx
Portals seem to crash when they are created outside of rendered tree. This modifies the structure of hover dialogs to match that one we use for modal dialogs.
> [FIX] Do not create portals outside of components

- pandora-client-web/src/components/chatroom/chatInput.tsx
- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
- pandora-client-web/src/components/chatroom/chatRoomDevice.tsx
This adds following two small improvements:
- Increases threshold between dragging and clicking on character/device from 100ms to standard 400ms
- Modifies labels of options in the select-style chat mode selector
> [CHANGE] Small chatroom improvements

- pandora-client-web/src/components/chatroomSelect/chatroomSelect.tsx
- pandora-client-web/src/networking/socketio_directory_connector.ts
- pandora-client-web/test/mocks/error/errorMocks.ts
- pandora-client-web/test/mocks/networking/mockDirectoryConnector.ts
- pandora-common/src/networking/directory_client.ts
- pandora-server-directory/src/account/accountManager.ts
- pandora-server-directory/src/networking/manager_client.ts
adds the number of accounts and characters online right now to the top of the room list
> [ADD] in-game online numbers

- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-client-web/src/common/useEvent.ts
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/definitions.ts
- pandora-common/src/assets/state/characterState.ts
- pandora-common/src/character/restrictionsManager.ts
> [FEATURE] device pose preset and exit pose

- pandora-client-web/src/components/chatroomSelect/chatroomSelect.scss
- pandora-client-web/src/components/chatroomSelect/chatroomSelect.tsx
- pandora-client-web/src/components/wiki/pages/intro.tsx
- pandora-common/src/chatroom/room.ts
- pandora-server-directory/src/account/accountManager.ts
- pandora-server-directory/src/account/character.ts
- pandora-server-directory/src/room/room.ts
Fixes and changes online counter that did not work due to last PR.
Also highlights and counts offline characters in the room search list differenty.
> [CHANGE] online and offline counter

- .github/workflows/pr.yml
Example of this can be seen in #399.
> [DEV] Fix race condition in automation task

- pandora-client-web/src/character/character.ts
- pandora-client-web/src/character/player.ts
- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
- pandora-client-web/src/components/chatroom/contextMenus/deviceContextMenu.tsx
- pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemRoomDevice.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeBodySizeView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeExpressionsView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitsView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/components/wardrobe/wardrobe.tsx
- pandora-client-web/src/components/wardrobe/wardrobeBody.tsx
- pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
- pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
- pandora-client-web/src/components/wardrobe/wardrobeTypes.ts
- pandora-client-web/src/editor/graphics/character/appearanceEditor.ts
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/test/character/character.test.ts
- pandora-client-web/test/character/player.test.ts
- pandora-common/src/character/index.ts
- pandora-common/src/event.ts
- pandora-common/src/networking/client_shard.ts
- pandora-common/src/networking/shard_client.ts
- pandora-server-directory/src/database/dbHelper.ts
- pandora-server-shard/src/character/character.ts
- pandora-server-shard/src/room/room.ts
~~**Depends on**: [pandora-assets#158](https://github.com/Project-Pandora-Game/pandora-assets/pull/158)~~
Resolves: #105 
Adds options to rotate character and offset it by arbitrary amount in Y direction inside a room.
Both of these modifiers are ignores inside wardrobe.
Rotation is implemented as bone, so assets can react to it. Y offset is implemented as additional field to the character's room position.
> [FEATURE] Character rotation and manual Y offset

- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
Similar problem as to the one fixed in #407. Bug introduced in #402.
Before 402 the swap was happening automatically in `GraphicsCharacter`. This makes it happen outside too.
> [FIX] Fix culling beak broken on characters with filters applied

- pandora-client-web/src/components/header/leaveButton.tsx
- pandora-common/src/networking/client_directory.ts
- pandora-common/src/networking/directory_shard.ts
- pandora-server-directory/src/account/character.ts
- pandora-server-shard/src/networking/socketio_directory_connector.ts
> [FEATURE] require room device leave before room leave

- pandora-client-web/src/components/chatroom/chatInput.tsx
- pandora-client-web/src/components/chatroom/chatroom.tsx
- pandora-client-web/src/components/gameContext/gameContextProvider.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/components/wiki/pages/intro.tsx
Fixes #310.
Also fixes a few wrongly positioned element warnings.
> [FIX] Preserve chat input mode when switching screens

- pandora-client-web/src/components/chatroomAdmin/chatroomAdmin.scss
- pandora-client-web/src/components/chatroomAdmin/chatroomAdmin.tsx
- pandora-client-web/src/components/dialog/dialog.scss
- pandora-client-web/src/components/dialog/dialog.tsx
This makes the tag filter UI work using the new tags. It works, though it only filters one tag at the moment and the UI is pretty jank, so it's definitely a work-in-progress.
> [ADD] Background tag filtering UI

- pandora-client-web/src/common/useKeyDownEvent.ts
- pandora-client-web/src/components/characterSafemode/characterSafemode.tsx
- pandora-client-web/src/components/chatroomAdmin/chatroomAdmin.tsx
- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/components/directMessages/directMessages.scss
- pandora-client-web/src/components/directMessages/directMessages.tsx
- pandora-client-web/src/components/gameContext/directMessageChannelProvieder.tsx
- pandora-client-web/src/components/releationships/relationships.tsx
- pandora-client-web/src/networking/directMessageManager.ts
- pandora-common/src/gameLogic/interactions/interactionSubsystemServer.ts
- pandora-server-directory/package.json
- pandora-server-directory/src/logging.ts
- pandora-server-shard/package.json
- pandora-server-shard/src/character/character.ts
- pandora-server-shard/src/logging.ts
- pnpm-lock.yaml
Fixes:
- null dereference if invalid DM is selected
- initial fixup on permission is not saved
remove `axios` as `fetch` is now stable in node
minor UI improvement on not found account for DMs
> [FIX] minor bugs

- pandora-client-web/src/components/chatroom/commands.ts
- pandora-client-web/src/components/chatroom/commandsHelpers.ts
- pandora-client-web/src/components/chatroom/contextMenus/characterContextMenu.tsx
- pandora-client-web/src/components/common/link/externalLink.tsx
- pandora-client-web/src/components/wiki/pages/contact.tsx
- pandora-client-web/src/components/wiki/pages/history.tsx
- pandora-common/src/chatroom/chatActions.ts
- pandora-common/src/networking/client_shard.ts
- pandora-server-shard/src/networking/manager_client.ts
- Adds a command `rockpaperscissors` that lets characters in the same chat room play it together in a secure way.
- Some minor random improvements/fixes
> [FEATURE] rock paper scissors command

- pandora-client-web/src/components/Eula/index.tsx
- pandora-client-web/src/components/characterSelect/characterSelect.scss
- pandora-client-web/src/components/characterSelect/characterSelect.tsx
- pandora-client-web/src/components/common/button/domIcons.scss
- pandora-client-web/src/components/common/button/domIcons.tsx
- pandora-client-web/src/components/common/tabs/tabs.scss
- pandora-client-web/src/components/dialog/dialog.tsx
- pandora-client-web/src/components/header/Header.tsx
- pandora-client-web/src/components/header/HeaderButton.tsx
- pandora-client-web/src/components/header/header.scss
- pandora-client-web/src/components/header/leaveButton.scss
- pandora-client-web/src/components/header/leaveButton.tsx
- pandora-client-web/src/components/releationships/relationships.scss
- pandora-client-web/src/components/versionCheck/versionCheck.tsx
- pandora-client-web/src/components/wardrobe/wardrobe.scss
- pandora-client-web/src/components/wiki/wiki.scss
- pandora-client-web/src/editor/editorContextProvider.tsx
- pandora-client-web/src/graphics/graphicsScene.tsx
- pandora-client-web/src/index.scss
- pandora-client-web/src/index.tsx
- pandora-client-web/src/routing/Routes.tsx
- pandora-client-web/src/styles/mediaQueries.ts
Ref: #68 
Adds ability to collapse the header buttons into "hamburger" menu when the screen is narrow (e.g. on phones in portrait mode).
Also attempts to fix pinch issues with graphics viewport.
> [FEATURE] Collapsable header

- pandora-client-web/src/components/chatroom/chatRoomDevice.tsx
- pandora-client-web/src/editor/components/wardrobe/wardrobe.tsx
- pandora-common/src/assets/definitions.ts
Adds possibility to rotate a character while in a room device slot. Also adds a property to configure the rotation pivot to the device graphics definition.
As a small bonus adds buttons to generate random body/clothing to the editor.
> [FEATURE] Enable character rotation inside room device

- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-client-web/src/components/chatroom/chatroomMessages.tsx
- pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/appearanceValidation.ts
- pandora-common/src/assets/asset.ts
- pandora-common/src/assets/assetManager.ts
- pandora-common/src/assets/definitions.ts
- pandora-common/src/assets/item.ts
- pandora-common/src/assets/properties.ts
- pandora-common/src/character/restrictionsManager.ts
This PR merges the underused asset slot system into the attribute system, enhancing it to support all previous use-cases. It also adds a new system for "state flags" allowing items to more easily enforce internal module state consistency.
> [REFACTOR] Merge slot system into attribute system

- pandora-common/src/logging.ts
- pandora-server-directory/src/index.ts
- pandora-server-directory/src/logging.ts
- pandora-server-directory/test/logging.test.ts
- pandora-server-shard/src/index.ts
- pandora-server-shard/src/logging.ts
- pandora-server-shard/test/logging.test.ts
Avoid blocking on log writes if disk is not keeping up.
> [CHANGE] Make logging to file asynchronous

- CONTRIBUTING.md
Adds a file regarding contributing guidelines.
> [DEV] Add contributing guidelines

- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
- pandora-client-web/src/components/chatroom/chatRoomDevice.tsx
- pandora-client-web/src/components/chatroom/chatRoomScene.tsx
- pandora-client-web/src/components/gameContext/chatRoomContextProvider.tsx
- pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemRoomDevice.tsx
- pandora-client-web/src/components/wardrobe/wardrobe.scss
- pandora-client-web/src/components/wardrobe/wardrobe.tsx
- pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
- pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
- pandora-client-web/src/components/wardrobe/wardrobeItems.tsx
- pandora-client-web/src/components/wardrobe/wardrobeTypes.ts
- pandora-client-web/src/editor/components/wardrobe/wardrobe.tsx
Adds a preview to the room inventory wardrobe, similar to the character wardrobe.
> [FEATURE] Room inventory wardrobe preview

- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/graphics/graphicsSuspense/graphicsSuspense.tsx
- pandora-client-web/src/graphics/useTexture.ts
Adds a suspense-like component that hides children if any child uses `useTexture` that didn't yet load.
Also has mechanism for avoiding flickering by not hiding the children even if it requested again, after a second after creation and everything being loaded.
And adds it to the characters.
> [FEATURE] Graphics suspense

- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
Fixes a regression introduced in #477.
> [FIX] Fix character movement by properly forwarding ref to the display object

- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/networking/directMessageManager.ts
- pandora-common/src/character/characterData.ts
- pandora-common/src/chatroom/chat.ts
- pandora-common/src/inputLimits.ts
- pandora-common/src/networking/client_directory.ts
- pandora-common/src/networking/client_shard.ts
- pandora-common/src/validation.ts
- pandora-server-directory/src/database/databaseStructure.ts
update #432 to respect changes
> [ADD] further length checks

- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-client-web/src/character/character.ts
- pandora-client-web/src/components/characterRestrictionOverride/characterRestrictionOverride.tsx
- pandora-client-web/src/components/characterSafemode/characterSafemode.tsx
- pandora-client-web/src/components/chatroom/chatroomControls.tsx
- pandora-client-web/src/components/gameContext/gameContextProvider.tsx
- pandora-client-web/src/components/header/leaveButton.tsx
- pandora-client-web/src/components/wardrobe/wardrobe.tsx
- pandora-client-web/src/components/wardrobe/wardrobeUtils.ts
- pandora-client-web/src/editor/components/wardrobe/wardrobe.tsx
- pandora-client-web/src/editor/editor.tsx
- pandora-common/src/assets/appearance.ts
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/item.ts
- pandora-common/src/assets/state/characterState.ts
- pandora-common/src/character/restrictionsManager.ts
- pandora-common/src/chatroom/chatActions.ts
- pandora-server-shard/src/networking/socketio_directory_connector.ts
> [FEATURE] timeout mode

- pandora-client-web/src/components/chatroom/chat.tsx
- pandora-client-web/src/components/chatroom/chatInput.tsx
- pandora-client-web/src/components/chatroom/chatroom.scss
> [FEATURE] mark edited message, scroll on mode change

- pandora-client-web/src/components/chatroom/commands.ts
- pandora-client-web/src/components/chatroom/contextMenus/characterContextMenu.tsx
- pandora-client-web/src/components/chatroomAdmin/chatroomAdmin.scss
- pandora-client-web/src/components/chatroomAdmin/chatroomAdmin.tsx
- pandora-server-directory/src/room/room.ts
fixes #492
(admins who are only admins due to development auto admin feature can be banned and kicked)
> [FIX] warn user if ban/kick would fail due to the target being an admin

- pandora-common/src/assets/item.ts
> [FIX] password locks should be case insensitive

- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-client-web/src/components/chatroom/chatRoomDevice.tsx
- pandora-client-web/src/components/chatroom/chatRoomScene.tsx
- pandora-client-web/src/components/chatroom/contextMenus/deviceContextMenu.tsx
- pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemRoomDevice.tsx
- pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
- pandora-client-web/src/components/wardrobe/wardrobeUtils.ts
- pandora-common/src/assets/appearanceActionProcessingContext.ts
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/appearanceValidation.ts
- pandora-common/src/assets/item.ts
resolves #494
resolves #455 (position is preserved even if background changes)
(currently deployed devices should stay deployed after the change)
> [CHANGE] device deployment improvements

- pandora-common/src/assets/modules/common.ts
- pandora-common/src/assets/modules/lockSlot.ts
- pandora-common/src/assets/modules/storage.ts
- pandora-common/src/assets/modules/typed.ts
- pandora-common/src/character/restrictionsManager.ts
- pandora-common/src/gameLogic/interactions/_interactionConfig.ts
> [ADD] more module interaction permissions

- pandora-client-web/src/character/character.ts
- pandora-client-web/src/components/chatroom/chatRoomDevice.tsx
- pandora-client-web/src/components/chatroom/chatRoomScene.tsx
- pandora-client-web/src/components/chatroom/chatroom.scss
- pandora-client-web/src/components/chatroom/chatroom.tsx
- pandora-client-web/src/components/chatroom/chatroomControls.tsx
- pandora-client-web/src/components/chatroom/contextMenus/deviceContextMenu.tsx
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/effects.ts
> [CHANGE] better room construction

- pandora-client-web/src/components/wardrobe/views/wardrobeItemView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitView.tsx
- pandora-client-web/src/components/wardrobe/wardrobe.scss
- pandora-client-web/src/components/wardrobe/wardrobeBody.tsx
- pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
- pandora-client-web/src/components/wardrobe/wardrobeItems.tsx
Adds a meter to the wardrobe's usage indicators, making them look nicer.
> [FEATURE] Items and storage usage meter

- pandora-common/src/assets/effects.ts
- pandora-common/src/character/restrictionsManager.ts
- pandora-common/src/character/speech.ts
- pandora-common/test/character/speech.test.ts
- pandora-server-shard/src/character/character.ts
(I have yet to test it with some actual assets)
> [FEATURE] hearing impairment

- pandora-common/src/assets/definitions.ts
- pandora-common/src/character/assetPreferences.ts
only allow "maybe" as an override
> [ADD] definition based override for asset preference

- pandora-common/src/logging.ts
- pandora-server-directory/src/account/accountManager.ts
- pandora-server-directory/src/account/accountSecure.ts
- pandora-server-directory/src/index.ts
- pandora-server-directory/src/logging.ts
- pandora-server-shard/src/index.ts
- pandora-server-shard/src/logging.ts
> [FEATURE] Audit log

- pandora-common/src/space/room.ts
- pandora-server-shard/src/character/character.ts
- pandora-server-shard/src/spaces/publicSpace.ts
- pandora-server-shard/src/spaces/space.ts
- Do not reset character position in some cases
- Better initial position
> [FIX] Room position improvements

- pandora-client-web/src/components/common/link/externalLink.tsx
Updates the dialog slightly, namely:
- Turns the link into a textarea for displaying the full link
- Replaces the two "open" buttons with a single button and a toggle to trust in the future
> [CHANGE] Small "untrusted link" dialog improvements

- pandora-client-web/src/components/gameContext/gameStateContextProvider.tsx
- pandora-client-web/src/components/settings/permissionsSettings.tsx
- pandora-client-web/src/ui/components/chat/chat.tsx
- pandora-common/src/assets/appearanceActionProcessingContext.ts
- pandora-common/src/gameLogic/interactions/_interactionConfig.ts
- pandora-common/src/gameLogic/interactions/interaction.ts
- pandora-common/src/gameLogic/permissions/permission.ts
- pandora-common/src/gameLogic/permissions/permissionData.ts
- pandora-common/src/gameLogic/permissions/permissionServer.ts
- pandora-common/src/networking/client_shard.ts
- pandora-common/src/networking/shard_client.ts
- pandora-server-directory/src/spaces/spaceManager.ts
- pandora-server-shard/src/networking/manager_client.ts
- pandora-server-shard/src/spaces/space.ts
resolves #17
anything that left over from the issue will be moved to separate issues that are not required for Beta 1
> [FEATURE] better permission prompt

- pandora-client-web/src/ui/components/chat/chatInput.tsx
Fixes regression from #551.
In #551 the chat input saving has been updated to run in the `onChange` event handler so it has up-to-date input instead of one state old input (which was particularly noticable if you backspaced the whole input). This however caused the saved state to not be properly updated when the content was set programmatically. This PR tries to fix all the programmatic update cases.
> [FIX] Properly update chat input saved state on send

- pandora-client-web/src/components/directMessage/directMessage.scss
- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/components/directMessages/directMessages.tsx
- pandora-client-web/src/components/wiki/pages/characters.tsx
- pandora-client-web/src/ui/screens/room/room.scss
- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.tsx
Changes the room chat and DM chat input fields according to the feedback of Sekkmer.
Also slightly improved the usability of adding new accounts to the DM list.
> [CHANGE] direct message UI

- pandora-client-web/src/components/gameContext/directoryConnectorContextProvider.tsx
- pandora-client-web/src/networking/socketio_shard_connector.ts
- pandora-client-web/src/routing/Routes.tsx
- pandora-client-web/src/ui/components/common/freeze.tsx
> [FIX] automatic login issues

- pandora-client-web/src/components/directMessage/directMessageCommandContext.tsx
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
- pandora-common/src/inputLimits.ts
- pandora-common/src/networking/client_directory.ts
- pandora-common/src/space/space.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/spaces/space.ts
> [FEATURE] Join Me invite for spaces

- pandora-client-web/src/components/wiki/pages/intro.tsx
- pandora-client-web/src/components/wiki/pages/items.tsx
Relates to https://github.com/Project-Pandora-Game/pandora/pull/593
> [CHANGE] outfit naming in the wiki

- pandora-client-web/src/networking/directMessageManager.ts
- pandora-common/src/inputLimits.ts
- pandora-common/src/networking/client_directory.ts
- pandora-common/src/utility.ts
- pandora-server-directory/package.json
- pandora-server-directory/src/account/accountDirectMessages.ts
- pandora-server-directory/src/database/databaseProvider.ts
- pandora-server-directory/src/database/databaseStructure.ts
- pandora-server-directory/src/database/mockDb.ts
- pandora-server-directory/src/database/mongoDb.ts
- pandora-server-directory/src/database/validatedCollection.ts
- pandora-server-directory/src/networking/manager_client.ts
- pnpm-lock.yaml
reduce direct message length by x10 to 2500 characters
ensure that only 50 messages are saved at most for a given conversation
store full conversion in a single object in database
> [FEATURE] limit dms

- pandora-client-web/src/common/anchorAutoscroll.tsx
- pandora-client-web/src/common/anchorHighlight.scss
- pandora-client-web/src/components/common/tabs/tabs.tsx
- pandora-client-web/src/components/gameContext/gameContextProvider.tsx
- pandora-client-web/src/components/wiki/pages/characters.tsx
- pandora-client-web/src/components/wiki/pages/intro.tsx
- pandora-client-web/src/components/wiki/pages/items.tsx
- pandora-client-web/src/components/wiki/pages/safety.tsx
- pandora-client-web/src/components/wiki/pages/spaces.tsx
- pandora-client-web/src/editor/editorContextProvider.tsx
Changes all wiki links from <a> to <Link> and fixes the issue that the header links forced a reload.
> [FIX] wiki links

- pandora-client-web/src/editor/editor.tsx
- pandora-client-web/src/editor/index.tsx
- pandora-tests/test/eula.test.ts
This fixes a crash introduced in #608
> [FIX] Move editor browser router above editor context provider

- pandora-client-web/src/components/wiki/pages/intro.tsx
- pandora-server-directory/src/account/account.ts
- pandora-server-directory/src/logging.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/spaces/space.ts
resolves #82 (even more)
This adds more directory server logging, some going to the audit log that Sekkmer implemented.
> [ADD] More audit logging

- pandora-client-web/src/components/common/button/button.scss
- pandora-client-web/src/components/common/button/button.tsx
- pandora-client-web/src/components/settings/characterSettings.tsx
- pandora-common/src/networking/client_directory.ts
- pandora-server-directory/src/account/account.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/test/networking/connection_client.test.ts
- only allow deleting currently connected character
- require current password for security
- multi step process in UI to prevent accidental deletion
> [FEATURE] character delete

- pnpm-lock.yaml
Regenerates the dependencies lockfile from scratch to get some ancient transitive dependencies more up-to-date.
> [CHORE] Regenerate dependencies lockfile

- pandora-client-web/src/components/versionCheck/versionCheck.tsx
Fixes the button layout in the version check dialog. Also slightly modifies its text to be a bit more clear.
> [FIX] Fix version check dialog layout

- pandora-client-web/src/ui/components/chat/commands.ts
- pandora-common/src/commands/executor.ts
> [ADD] empty whisper unset the current target

- pandora-server-directory/src/account/accountContacts.ts
this may or may not fix the inconsistent status in contacts (#639) but it should certainly help
> [FIX] correctly set updating guard to default state

- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.tsx
> [ADD] user readable error for space join results

- pandora-client-web/src/editor/assets/assetManager.ts
Updates the template to match changes in the asset repository.
> [DEV] Update editor asset template

- pandora-client-web/src/ui/components/chat/chatMessages.tsx
- pandora-client-web/src/ui/components/chat/chatParser.ts
> [FIX] _ should be displayed as is in character name and assets

- pandora-client-web/src/components/profileScreens/accountProfile.tsx
- pandora-client-web/src/components/profileScreens/characterProfile.tsx
- pandora-client-web/src/components/profileScreens/profileScreens.scss
- pandora-client-web/src/styles/_constants.scss
Uses the same visual style and fonts for profile and profile editor.
This allows for the creation of ASCII art, visually consistent indentation ect.
> [CHANGE] Unify style of profile editor and display

- pandora-client-web/src/assets/icons/triangle_down.svg
- pandora-client-web/src/assets/icons/triangle_up.svg
- pandora-client-web/src/components/common/colorInput/colorInput.tsx
- pandora-client-web/src/components/dialog/dialog.tsx
- pandora-client-web/src/components/help/contextHelpButton.tsx
- pandora-client-web/src/components/settings/permissionsSettings.tsx
- pandora-client-web/src/components/wardrobe/poseDetail/storedPosePresets.scss
- pandora-client-web/src/components/wardrobe/poseDetail/storedPosePresets.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-common/src/assets/item/unified.ts
- pandora-common/src/assets/state/characterStatePose.ts
- pandora-common/src/inputLimits.ts
- pandora-common/src/networking/client_directory.ts
- pandora-common/src/networking/directory_client.ts
- pandora-server-directory/src/account/account.ts
- pandora-server-directory/src/database/databaseStructure.ts
- pandora-server-directory/src/networking/manager_client.ts
- store up to 20 presets / account
- import export
> [FEATURE] pose preset storage

- pandora-client-web/src/components/wardrobe/poseDetail/storedPosePresets.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/editor/components/bones/bones.tsx
- pandora-client-web/src/graphics/def.ts
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-common/src/assets/appearance.ts
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/appearanceLimit.ts
- pandora-common/src/assets/definitions.ts
- pandora-common/src/assets/graphics/graphics.ts
- pandora-common/src/assets/state/characterStatePose.ts
add user configurable side order for arms, structure added for upper arm in case we want to split arms more in the future
this PR split the working arm order code changes from #622
> [FEATURE] arm side order

- pandora-client-web/src/components/wardrobe/itemDetail/_wardrobeItemDetail.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeItemView.tsx
tested with and without `React.StrictMode`
> [FIX] focus previous on lock slot

- pandora-server-directory/src/services/github/githubVerify.ts
fix #673
handle oktokit errors properly
(this does not resolve issue where beta-access members who made commits do not get any roles: #725)
> [FIX] GitHub verify

- pandora-client-web/src/assets/assetManager.ts
- pandora-client-web/src/assets/graphicsManager.ts
- pandora-client-web/src/editor/assetLoader.ts
- pandora-common/src/assets/graphics/graphics.ts
Add option to support `AVIF` or `webp` images
> [FEATURE] alternative image format support

- pandora-client-web/src/ui/screens/room/roomControls.tsx
Fixes #716 
The proposed order is
- Player
- Online friends & online characters from player account
- Online non-friends
- Offline friends & offline characters from player account
- Offline non-friends
The ordering within groups is from last to join to first to join; because in JS sets preserve insertion order and sorting is stable.
Right now, the useMemo is kinda useless because `characters` changes everytime someone moves around in the space, causing the whole component as well as the useMemo to run again. I think it might be a good idea to separate the Character type in two in order to avoid re-rendering the whole component when the list hasn't changed.
> [FEATURE] Sorting of room characters list

- pandora-server-shard/src/assets/assetManager.ts
Checks that the `current` file is not empty and points to an existing file before attempting reload.
Fully fixing the race condition will require more changes in the asset repo.
> [FIX] Check new asset definitions are valid before trying to load them

- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/item/unified.ts
- pandora-common/src/inputLimits.ts
> [CHANGE] limit item custom name characters

- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/appearanceValidation.ts
- pandora-common/src/assets/assetManager.ts
- pandora-common/src/assets/item/_internal.ts
- pandora-common/src/assets/item/base.ts
- pandora-common/src/assets/item/unified.ts
- pandora-common/src/assets/state/characterState.ts
add `spwanedBy: CharacterId` to all items, property is server only and never sent to the client
> [FEATURE] item spawned by property

- pandora-common/src/assets/item/lock.ts
property must be present to lock without password so all current locks that do not have this property will behave as if they forgot the saved password and must be set a new password
preparation for #717
> [ADD] `passwordSetBy` as id of the character who set password on locks as hidden data

- pandora-client-web/src/components/wardrobe/itemDetail/_wardrobeItemDetail.tsx
closes https://github.com/Project-Pandora-Game/pandora/issues/759
> [FIX] wardrobe editing item screen closing

- pandora-client-web/src/components/common/form/form.tsx
- pandora-client-web/src/components/common/form/formFieldCaptcha.tsx
- pandora-client-web/src/components/gameContext/directoryConnectorContextProvider.tsx
- pandora-client-web/src/components/login/forms/forgotPasswordForm.tsx
- pandora-client-web/src/components/login/forms/registrationForm.tsx
- pandora-client-web/src/components/login/forms/resendVerificationAdvancedForm.tsx
- pandora-client-web/src/components/login/forms/resendVerificationForm.tsx
I also set `sentry={ false }` tried it locally and it works but not quite sure if this count as removing `Sentry` as the loader package doesn't use dynamic import so the source for sentry will still be present
ref: #676
> [CHANGE] lazy load hcaptcha

- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/character/restrictionTypes.ts
> [FIX] prevent character randomize action in room devices

- pandora-common/src/assets/appearanceValidation.ts
- pandora-common/src/assets/properties.ts
This change adds a new attribute `limit` to assets that denotes, how many items o…f this kind can be worn at the same time.
As a proof of concept I added a limit of 20 to the pantyhose asset:
> [FEATURE] New attribute 'limit' 

- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-client-web/src/components/wardrobe/modules/wardrobeModuleLockSlot.tsx
- pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
- pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
- pandora-client-web/src/editor/components/wardrobe/wardrobe.tsx
- pandora-common/src/assets/appearanceActionProblems.ts
- pandora-common/src/assets/appearanceActionProcessingContext.ts
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/appearanceHelpers.ts
- pandora-common/src/assets/item/_internal.ts
- pandora-common/src/assets/item/lock.ts
- pandora-common/src/assets/modules.ts
- pandora-common/src/assets/modules/common.ts
- pandora-common/src/assets/modules/lockSlot.ts
- pandora-common/src/assets/state/globalState.ts
- pandora-common/src/networking/client_shard.ts
- pandora-server-shard/src/networking/manager_client.ts
> [FEATURE] show lock password

- pandora-client-web/src/components/accountContacts/accountContacts.tsx
If the list of contacts grows too long, one couldn't scroll the list. This issue is fixed with this PR.
> [ADD] Add a scrollbar to the list of contacts

- .github/pull_request_template.md
_None_
Added a pull request template to make the PR descriptions more standardized and avoid people filing PRs with empty descriptions.
_None_
> [DEV] Add PR template

- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
_None_
Makes the "Control arms individually" persistent in localstorage instead of having it reset each time the posing tab is unfocused.
```md
- The "Control arms individually" toggle now remembers how it was set instead of disabling itself all the time
```
> [CHANGE] Persist "Control arms individually" setting in pose menu

- pandora-client-web/src/components/directMessages/directMessages.tsx
ref #792 
Fixes a bug that multi-digit account ids didn't get parsed properly
```md
Fixes:
- You can once more open DMs to users with multi-digit account ids
```
> [FIX] Properly parse multidigit account ids

- pandora-client-web/src/components/dialog/dialog.tsx
- pandora-client-web/src/services/accountLogic/directMessages/directMessageChat.ts
- pandora-client-web/src/ui/screens/spaceJoin/spaceJoin.scss
- pandora-client-web/src/ui/screens/spaceJoin/spaceJoin.tsx
- pandora-common/src/networking/client_directory.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/spaces/space.ts
_None_
This PR fixes an issue that caused `_` characters to be eaten by formatting, even inside links in DMs.
Also improves how are invites through DMs handled by showing more detailed errors and allowing invite's author to always resolve it, if it is still valid.
Also fixes invalid message warning when invite is read inside DM without a selected character.
Also fixes click events bubbling outside of modal dialogs (usually clicking the button that opened them and closing them immediately, no matter where you click).
```md
Fixes:
- Links sent through DMs (notably space invites) no longer get randomly split in half and thus broken
- Invalid space invitations sent through DMs and/or normal chat now display more detailed message about why they are invalid
- Clicking empty space inside …
```
> [FIX] Allow parsing links in DMs

- pandora-client-web/src/graphics/baseComponents/container.ts
- pandora-client-web/src/graphics/graphicsSceneRenderer.tsx
_None_
Fixes the two errors reported so far.
```md
Fixes:
- Fixed crash when switching to another screen while chatroom is still rendering
- Fixed character rotation not working
```
> [FIX] Pixi render crash when changing screen during render and character rotation fix

- pandora-client-web/src/graphics/graphicsSceneRenderer.tsx
_None_
At the moment there is a race condition in the renderer that can cause the canvas to be rendered blank. This can be rarely seen while switching between wardrobe and room view, or room view and character profile.
This PR updates the logic to properly queue render instead of rushing it, trusting the reconciler to send update request if it is needed.
```md
Fixes:
- Fixed that switching between wardrobe, room and profile might rarely cause one of them to render blank until interacted with
```
> [FIX] Fix renderer sometimes rendering blank stage

- pandora-client-web/src/components/settings/settings.tsx
_None_
Fixes a typo in the new Notifications tab title and url chunk
Authored by: SandrinePDR
Fixes:
- Name of the notifications settings tab
> [FIX] Typo in the notifications tab title

- pandora-client-web/src/components/common/button/button.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitView.tsx
- pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
- pandora-client-web/src/graphics/graphicsSceneRenderer.tsx
- pandora-client-web/src/services/serviceProvider.tsx
_None_
Fixes wardrobe previews by forwarding service manager there
```md
Fixes:
- Fixed saved items previews in wardrobe
```
> [FIX] Fixes wardrobe previews

- pandora-client-web/src/editor/editorContextProvider.tsx
- pandora-client-web/src/editor/index.tsx
- pandora-client-web/src/editor/services/editorServices.ts
- pandora-client-web/src/editor/services/editorShardConnectionManager.ts
- pandora-client-web/src/services/clientServices.ts
- pandora-client-web/src/services/serviceProvider.tsx
- pandora-client-web/src/services/shardConnectionManager.ts
- pandora-common/src/services/service.ts
_None_
Adds service manager for editor and implements the currently required service to avoid errors in the editor.
```md
Fixes:
- Fixed Editor after the latest technical reworks
```
> [ADD] Service manager support for Editor

- package.json
- pandora-client-web/.eslintrc.json
- pandora-client-web/src/components/settings/accountSettings.tsx
- pandora-client-web/test/tsconfig.json
- pandora-client-web/test/tsconfig.setup.json
- pandora-client-web/tsconfig.json
- pandora-common/.eslintrc.json
- pandora-common/package.json
- pandora-common/tsconfig.base.json
- pandora-common/tsconfig.json
- pandora-server-directory/test/tsconfig.json
- pandora-server-directory/tsconfig.json
- pandora-server-shard/test/tsconfig.json
- pandora-server-shard/tsconfig.json
- pandora-tests/test/tsconfig.json
- pnpm-lock.yaml
_None_
Adds support for TS project references and ESLint project service, which should give muuuch better development experience if pandora-common build is not up-to-date or not built at all.
```md
- Improved tooling related to development: You should no longer see weird errors when you do changes in `pandora-common`, after starting the build for the first time, or when adding a new file.
```
> [DEV] Make use of TypeScript project references and ESLint project service

- pandora-client-web/.eslintrc.json
- pandora-client-web/src/graphics/room/contextMenus/deviceContextMenu.tsx
_None_
See changelog
```md
Fixes:
- Fixed that entering or leaving a room device would close the tab instead of only closing the popup menu
```
> [FIX] Do not close tab on room device enter/leave

- pandora-client-web/src/graphics/graphicsLayer.tsx
- pandora-client-web/src/graphics/room/roomCharacter.tsx
- pandora-client-web/src/graphics/room/roomDevice.tsx
- pandora-client-web/src/graphics/room/roomDeviceContext.tsx
- pandora-client-web/src/ui/screens/room/roomPermissionChecks.tsx
- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.tsx
- pandora-common/src/assets/item/roomDeviceWearablePart.ts
- pandora-common/src/assets/state/characterState.ts
- pandora-common/src/character/restrictionsManager.ts
_None_
Fixes few small issues regarding room devices and also removes a no longer valid tip.
```md
Fixes:
- Fixed posing overlay being misaligned if the character is in a room device
- Fixed movement overlay being available if the character is in a room device
- Fixed Room device's parts that are visible in character wardrobe not being colored correctly
- Fixed Room device's representation visible in character wardrobe not having the room device's ribbon (color strip)
- Removed an outdated tip regarding space visibility
```
> [FIX] Room device posing overlay and wardrobe coloring

- pandora-client-web/src/assets/graphicsLoader.ts
_None_
After updating to Pixi v8 and getting support for proper background asset loading, the service worker's fetch seems to require using absolute URL. This conflicts with our default development setup.
```md
Fixes:
- Fixed graphics not loading when running development version of Pandora locally
```
> [FIX] Convert relative URL to full one for URLGraphicsLoader

- pandora-client-web/src/components/settings/accountSettings.tsx
- pandora-client-web/src/components/settings/characterSettings.tsx
- pandora-client-web/src/components/settings/settings.scss
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/graphics/graphicsSettings.tsx
_None_
```md
- Added a setting to enable or disable character blinking
- Currently disabled by default until performance is improved
```
> [FEATURE] Add setting for enabling/disabling character blinking

- pandora-client-web/src/assets/assetGraphicsCalculations.ts
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/editor/graphics/character/appearanceEditor.ts
- pandora-client-web/src/editor/graphics/draggable.tsx
- pandora-client-web/src/editor/graphics/layer/resultLayer.tsx
- pandora-client-web/src/editor/graphics/layer/setupLayer.tsx
- pandora-client-web/src/graphics/appearanceConditionEvaluator.ts
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/graphics/graphicsLayer.tsx
- pandora-client-web/src/graphics/graphicsSettings.tsx
- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.scss
- pandora-common/src/assets/appearance.ts
- pandora-common/src/assets/graphics/graphics.ts
- pandora-common/src/assets/state/characterStatePose.ts
_None_
This PR introduces several refactors and added caches that overall significantly improve performance of graphics character tree construction and updates.
```md
- Several performance improvements and optimizations that should allow for smoother experience whenever some character changes (especially if the change is so simple as a blink!)
- Enabled blinking by default
Fixes:
- Fixed space search layout being broken on Firefox 132+
```
> [CHANGE] Several performance optimizations about character graphics tree

- pandora-client-web/src/assets/assetManager.ts
- pandora-client-web/src/assets/graphicsLoader.ts
- pandora-client-web/src/graphics/baseComponents/mesh.tsx
- pandora-client-web/src/graphics/baseComponents/pixiViewport.tsx
- pandora-client-web/src/graphics/debugResourceRetention.ts
- pandora-client-web/src/graphics/graphicsAppManager.ts
- pandora-client-web/src/graphics/graphicsMaskLayer.ts
- pandora-client-web/src/graphics/graphicsScene.tsx
- pandora-client-web/src/graphics/graphicsSceneRenderer.tsx
- pandora-client-web/src/graphics/pixiSettings.ts
- pandora-client-web/src/graphics/reconciler/component.ts
- pandora-client-web/src/graphics/reconciler/element.ts
- pandora-client-web/src/graphics/room/roomCharacter.tsx
- pandora-client-web/src/graphics/room/roomDevice.tsx
_None_
Aims to remove memory leaks (at least the most major one currently) that happen whenever graphics updates.
Also adds code to cleanup on tab unload (because browsers somehow fail to do that) and slightly refactors some bits to improve performance.
```md
- Taught Pandora how to properly cleanup old graphics data, so Pandora should no longer use more and more memory each time graphics change
- Improved performance by reusing existing buffers whenever possible, instead of replacing them with new ones
```
> [FIX] Properly cleanup mesh geometry on changes and mesh destruction

- pandora-client-web/src/components/settings/graphicsSettings.tsx
- pandora-client-web/src/components/settings/settings.tsx
- pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemColor.tsx
- pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemRoomDevice.tsx
- pandora-client-web/src/components/wardrobe/templateDetail/wardrobeTemplateColor.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeBodySizeView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/config/Environment.ts
- pandora-client-web/src/editor/graphics/layer/setupLayer.tsx
- pandora-client-web/src/graphics/common/transitions/transitionHandler.ts
- pandora-client-web/src/graphics/common/transitions/transitionTimingFunctions.ts
- pandora-client-web/src/graphics/common/transitions/transitionedContainer.ts
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/graphics/graphicsLayer.tsx
- pandora-client-web/src/graphics/graphicsSceneRenderer.tsx
- pandora-client-web/src/graphics/graphicsSettings.tsx
- pandora-client-web/src/graphics/reconciler/component.ts
- pandora-client-web/src/graphics/reconciler/element.ts
- pandora-client-web/src/graphics/reconciler/tick.ts
- pandora-client-web/src/graphics/room/roomCharacter.tsx
- pandora-client-web/src/graphics/room/roomCharacterPosing.tsx
- pandora-client-web/src/graphics/room/roomDevice.tsx
- pandora-common/src/assets/state/characterState.ts
- pandora-common/src/assets/state/characterStatePose.ts
_None_
This PR adds smooth transitions for when something changes (character moves or changes pose).
Currently this is enabled only for characters (not for room devices or characters _in_ room devices) and only for the main room view (not in wardrobe).
Also implements setting to disable this, which defaults to "auto" = enabled unless system-wide "prefer-reduced-motion" is in effect.
```md
- Added transition animations to characters in the room:
- Moving or changing character's pose will now smoothly transition to the final pose instead of jumping instantly
- The transitions respect item limits, so if your movement is limited you might still jump instead of transitioning between the poses
- If you are in movement or posing mode, the transitions are very short to still let …
```
> [FEATURE] Graphics transitions

- pandora-client-web/src/components/common/form/form.scss
- pandora-client-web/src/components/directMessage/directMessage.scss
- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/components/gameContext/directMessageChannelProvieder.tsx
- pandora-client-web/src/components/login/forms/forgotPasswordForm.tsx
- pandora-client-web/src/components/login/forms/resetPasswordForm.tsx
- pandora-client-web/src/services/accountLogic/directMessages/directMessageChat.ts
- pandora-client-web/src/services/accountLogic/directMessages/directMessageManager.ts
- pandora-client-web/src/styles/globalUtils.scss
- pandora-client-web/test/components/login/authFormRouter.test.tsx
- pandora-common/src/networking/client_directory.ts
- pandora-server-directory/src/account/accountDirectMessages.ts
- pandora-server-directory/src/database/mockDb.ts
- pandora-server-directory/src/database/mongoDb.ts
_None_
Fixes bunch of problems regarding direct messages and encryption keys changing. See individual commits or changelog for more details.
```md
- Added warning to the password reset form, that resetting your password will clear all Direct Message history for both you and your conversation partners
Fixes:
- Several fixes for Direct Messages:
- Fixed history of direct messages not loading correctly if you got a direct message before ever opening direct messaging window during the current session
- Fixed properly showing when some messages in the conversation history are encrypted using old key (from before password reset), instead of showing a generic error
- Fixed server "forgetting" all but the last direct message for conversations that were started before either of …
```
> [FIX] Bunch of fixes regarding DMs and encryption keys changing

- pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
- pandora-client-web/src/graphics/common/transitions/transitionHandler.ts
- pandora-client-web/src/graphics/common/transitions/transitionedContainer.ts
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/graphics/room/roomCharacter.tsx
- pandora-client-web/src/graphics/room/roomDevice.tsx
_None_
Adds transitions for characters inside room devices (blocking the problematic ones), and fixes small bug regarding initial wardrobe viewport centering.
```md
- Enabled graphical transitions for standalone characters inside the wardrobe screen
- Enabled graphical transitions for characters inside room devices, with a few limitations:
- Characters move instantly when entering/exiting room device (this is simply too hard to make look nicely, currently)
- Some transitions are skipped as they can look rather weird. To be specific: following animations happen instantly: Turning around, movement up/down within a slot, rotating to the side
Fixes:
- Fixed wardrobe character preview not correctly centering on the character when wardrobe is opened.
```
> [ADD] Transitions for characters inside room devices

- pandora-common/src/assets/appearanceLimit.ts
_None_
Without this the pose limit can ignore values that are not ordered properly.
```md
Fixes:
- Fixed the pose limiting ignoring some allowed values for non-bone poses (e.g. leg state) if assets put them in specific order. This, for example, prevented sitting with "Fluffy Shoes", while it should have been possible.
```
> [FIX] Pose limit should sort values after translating them from enum

- pandora-client-web/src/components/dialog/dialog.tsx
- pandora-client-web/src/editor/components/previewCutter/previewCutter.tsx
- pandora-client-web/src/editor/editor.tsx
- pandora-client-web/src/editor/graphics/character/editorCharacter.tsx
- pandora-client-web/src/editor/graphics/editorScene.tsx
- pandora-client-web/src/editor/graphics/export/imageExporter.ts
- pandora-client-web/src/graphics/def.ts
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/graphics/graphicsLayer.tsx
- pandora-client-web/src/graphics/graphicsScene.tsx
- pandora-common/src/assets/graphics/graphics.ts
_None_
```md
Asset creation changes:
- Improved the "Preview Cutter" tool in Editor to automatically configure (most) of the body's layers for creating previews, while it is active.
Fixes:
- Fixed, that for some floating dialogs (such as help windows) clicking them would register as if clicking their containing element.
- Fixed (hopefully) preview cutter occasionally generating blank image.
```
> [ADD] Editor preview generation automatic layer state overrides

- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/components/wiki/pages/items.tsx
- pandora-client-web/src/editor/graphics/export/imageExporter.ts
- pandora-client-web/src/graphics/def.ts
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.tsx
- pandora-common/src/assets/graphics/conditions.ts
_None_
Allows for positioning arms above front hair or below back hair. These two options are marked as experimental, as they break with some hairs - this is likely  to be (mostly) resolved by arm split at elbow.
```md
- Added ability to freely position your hands above or below front and back hair.
- Note, that some combinations are marked as "experimental" and can lead to visual glitches, particularly if using long hair. While we are aware of this problem, there is no easy fix for it. Despite that we felt it is better to give the option to do so anyway, as there are cases where this works well.
- Updated several appearance validation messages to better convey that the action _would_ create an invalid state instead of referring to the current state.
- Added a note to …
```
> [ADD] Allow for positioning arms above or below hair

- .github/workflows/ci.yml
- .hooks/include.sh
- .vscode/tasks.json
- Dockerfile
- package.json
_None_
This fixes recent screwup of corepack shipping pinned keys, while npm registry rotated them.
I attempted to mitigate this into the future by just updating them every time from the npm endpoint.
This -technically- decreases security as they are no longer pinned, but we instead pin the hash of pnpm itself in our `packageManager` field.
_None_
> [FIX] Update corepack npm registry keys

- pandora-client-web/src/components/common/button/button.scss
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
_None_
```md
Fixes:
- Fixed the space configuration screen not being open-able after recent update
- Fixed that holding down on button with icon on mobile would bring up the icon's context menu
```
> [FIX] Fix space configuration being broken

- pandora-client-web/src/components/characterSelect/characterSelect.tsx
- pandora-common/src/networking/client_directory.ts
- pandora-common/src/networking/connection.ts
- pandora-server-directory/src/database/mongoDb.ts
- pandora-server-directory/src/networking/connection_client.ts
- pandora-server-directory/src/networking/connection_shard.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/networking/socketio_client_server.ts
- pandora-server-directory/src/networking/socketio_shard_server.ts
- pandora-server-directory/src/spaces/space.ts
- pandora-server-shard/src/networking/connection_client.ts
- pandora-server-shard/src/networking/manager_client.ts
- pandora-server-shard/src/networking/socketio_client_server.ts
_None_
```md
Fixes:
- Fixed that quick space admin actions (banning, promoting, allow-listing, ...) through character menu or chat commands might revert randomly after a while
- Improved handling of clients that disconnect even before finishing connect sequence
- Improved handling of "list own characters" request while not logged in
```
> [FIX] Properly save admin actions in space to database and small connecting handling fixes

- pandora-common/src/assets/item/base.ts
_None_
Quick fix from the last PR.
_None_
> [FIX] Use only relative paths in imports

- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-client-web/src/components/wardrobe/modules/wardrobeModuleLockSlot.tsx
- pandora-common/src/assets/modules.ts
- pandora-common/src/gameLogic/actionLogic/actionUtils.ts
- pandora-common/src/gameLogic/locks/lockData.ts
- pandora-common/src/gameLogic/locks/lockLogic.ts
- pandora-common/src/gameLogic/locks/lockSetup.ts
resolves #849 
Adds the necessary lock handling to support timer lock assets.
Authored by: Livie53
```md
- Added timer functionality to lock handling to support timer locks
```
> [FEATURE] Added timer functionality to locks

- .github/pull_request_template.md
- jest.config.cjs
- pandora-client-web/jest.config.js
- pandora-client-web/src/components/common/form/form.tsx
- pandora-client-web/src/components/common/link/externalLink.tsx
- pandora-client-web/src/components/common/tabs/tabs.tsx
- pandora-client-web/src/components/directMessage/directMessageCommandContext.tsx
- pandora-client-web/src/components/directMessages/directMessages.tsx
- pandora-client-web/src/components/profileScreens/profileScreens.tsx
- pandora-client-web/src/components/wiki/pages/contact.tsx
- pandora-client-web/src/components/wiki/pages/history.tsx
- pandora-client-web/src/editor/index.tsx
- pandora-client-web/src/index.tsx
- pandora-client-web/src/routing/Routes.tsx
- pandora-client-web/src/routing/config.ts
- pandora-client-web/src/routing/routingUtils.ts
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
- pandora-client-web/src/ui/screens/spaceJoin/spaceJoin.tsx
- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.tsx
- pandora-client-web/test/testUtils.tsx
- pandora-common/jest.config.js
- pandora-server-directory/jest.config.js
- pandora-server-shard/jest.config.js
ref #885
Updates routing code in preparation for updating to react-router v7.
Also does some small, mostly related changes:
- Change how are space invite URLs handled
- Make character profile screen use URL navigation for tabs
- Include referrer with Discord invite (it is anyway connected to Pandora already)
- Small update to PR template
```md
- Updated and cleaned up tabs URL routing code
```
> [CHORE] Update routing code

- pandora-client-web/src/components/wardrobe/views/characterModifiers/characterModifierInstanceLock.tsx
- pandora-client-web/src/components/wardrobe/wardrobeEffectsModifiers.tsx
- pandora-client-web/src/components/wiki/pages/characters.tsx
- pandora-common/src/assets/item/lock.ts
- pandora-common/src/chat/chatActions.ts
- pandora-common/src/gameLogic/actionLogic/appearanceActionProcessingContext.ts
- pandora-common/src/gameLogic/actionLogic/characterModifierActions.ts
- pandora-common/src/gameLogic/assetPreferences/assetPreferencesSubsystemServer.ts
- pandora-common/src/gameLogic/character/characterServer.ts
- pandora-common/src/gameLogic/characterModifiers/characterModifierData.ts
- pandora-common/src/gameLogic/characterModifiers/characterModifierInstance.ts
- pandora-common/src/gameLogic/characterModifiers/characterModifierLocks.ts
- pandora-common/src/gameLogic/characterModifiers/characterModifiersSubsystemServer.ts
- pandora-common/src/gameLogic/locks/lockLogic.ts
- pandora-server-shard/src/character/character.ts
- pandora-server-shard/src/networking/manager_client.ts
_None_
See changelog
```md
- Modifier locks and normal item locks are now one and the same
- Modifier lock types are now affected by lock item preferences and relevant permissions
- This will cause one-time deletion of all locks on existing modifiers, as the underlying structure changed significantly with no easy way to migrate the data. We apologize for this inconvenience.
```
> [CHANGE] Use assets for modifiers locking

- pandora-common/src/assets/modules/lockSlot.ts
resolves https://github.com/Project-Pandora-Game/pandora/issues/874
depends on https://github.com/Project-Pandora-Game/pandora-assets/pull/400
Removes distinction between no lock and unlocked lock for lock slots.
Authored by: Livie53
```md
- Unlocked locks are now treated the same as the lock not being present at all. This means that only a locked locks affect the item.
```
> [CHORE] Removed "occupied" from possible lock slot states

- package.json
- pandora-client-web/src/editor/graphics/export/imageExporter.ts
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/graphics/layers/graphicsLayerAlphaImageMesh.tsx
- pandora-client-web/src/graphics/layers/graphicsLayerCommon.tsx
- pandora-client-web/src/graphics/layers/graphicsLayerMesh.tsx
- pandora-client-web/src/graphics/room/roomCharacter.tsx
- pandora-common/src/assets/state/characterStateTypes.ts
_None_
It appears pixi finally fixed the filters+culling bug in the latest version, which makes it possible to remove our existing workaround.
Also updated new settings for pnpm.
```md
Fixes:
- Fixed graphical issue, where characters with applied filters (e.g. ghosts or while wearing a blindfold) would appear invisible or otherwise broken, on specific browser+platform+hardware configurations
```
> [FIX] Update graphics code after latest pixi.js changes

- pandora-client-web/package.json
- pandora-client-web/webpack.config.ts
- pnpm-lock.yaml
_None_
Turns out some transforms css nano does are not entirely safe. In this case a value `0%` was replaced by `0`, which normally makes sense, but it breaks the CSS in case of being used in `@property` declaration.
Instead of trying to hunt down the exact responsible optimization, I decided to simply tune down minification to the `lite` preset, which for the most part only minimizes whitespace.
This in turn increased CSS bundle size by roughly 2% (~2kb), which I think is more than acceptable price to pay for having fewer possible bugs.
```md
Fixes:
- Fixed the light animation in character selection screen jumping weirdly
```
> [FIX] Use lite preset for CSS nano

- pandora-server-directory/src/database/mongoDb.ts
_None_
Fixes few small mistakes caught when testing migration from previous PR on production data.
_None_
> [FIX] Fix mistakes in new migrations

- pandora-client-web/src/graphics/room/roomDevice.tsx
ref #938
Fixes a mistake in rooms with no ceiling.
```md
Fixes:
- Fixed that room devices would get clipped in a weird way in rooms with no visible ceiling
```
> [FIX] Clamp room devices to image edge if the room has no ceiling

- pandora-common/src/assets/state/characterStatePose.ts
- pandora-server-directory/src/database/databaseStructure.ts
> [FIX] Drop invalid pose preset parts instead of dropping all presets

- pandora-client-web/src/components/gameContext/directoryConnectorContextProvider.tsx
- pandora-client-web/src/components/wardrobe/poseDetail/customPosePresetStorage.ts
- pandora-client-web/src/components/wardrobe/poseDetail/storedPosePresets.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitView.tsx
- pandora-client-web/src/networking/directoryConnector.ts
- pandora-client-web/test/components/gameContext/directoryConnectorContextProvider.test.ts
_None_
```md
Fixes:
- Fixed that stored pose presets would not load if you weren't already logged in during Pandora's load
- Fixed rare issue where some changes to pose presets, characters, or saved items would not be detected if you experienced a small disconnect while those were done in another tab/using another device
```
> [FIX] Refetch stored pose presets when current account changes

- pandora-client-web/src/editor/graphics/export/imageExporter.ts
- pandora-client-web/src/graphics/baseComponents/customMesh.tsx
- pandora-client-web/src/graphics/baseComponents/mesh.tsx
- pandora-client-web/src/graphics/graphicsSceneRenderer.tsx
- pandora-client-web/src/graphics/room/roomScene.tsx
- pandora-common/src/assets/item/_internal.ts
- pandora-common/src/assets/item/bodypart.ts
- pandora-common/src/assets/item/roomDevice.ts
- pandora-common/src/assets/item/roomDeviceWearablePart.ts
- pandora-common/src/gameLogic/actionLogic/actions/transfer.ts
_None_
See changelog
```md
Fixes:
- Moving a deployed room device between room inventories now properly checks that you are a space admin
- Fixed a crash that occasionally occurred when moving from a 3D-Box room with large walls directly to another 3D-Box room with either small walls or walls with big tiles and then triggered a new frame render, e.g. by zooming in
- Fixed an error that occasionally occurred when moving from a 3D-Box room with small walls directly to another 3D-Box room with either large walls or walls with small tiles, that caused the walls in question to get stuck on the screen instead of moving with the camera
- Improved handling of errors during graphics rendering - they will no longer crash the whole of Pandora, but only the relevant graphics view …
```
> [FIX] Crash fix in render when mesh changes size and prevent non-admin moving deployed room devices

- pandora-client-web/src/components/wardrobe/views/characterModifiers/characterModifierTypeDetailsView.tsx
_None_
```md
Fixes:
- Fixed that menu to create modifier would not scroll even if too big to fit into a screen
```
> [FIX] Add scrollbar to modifier type details

- pandora-client-web/src/common/calculationQueue.ts
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/components/wardrobe/wardrobeCheckQueue.ts
- pandora-common/src/assets/appearanceLimit.ts
- pandora-common/src/assets/appearanceValidation.ts
- pandora-common/src/assets/properties.ts
- pandora-common/src/assets/roomValidation.ts
- pandora-common/src/assets/state/characterState.ts
- pandora-common/src/logging/logger.ts
- pandora-common/src/utility/misc.ts
_None_
```md
- Several performance optimizations related to logic and validation:
- Streamlined item validation, speeding it up roughly by order of magnitude
- Started caching character validation, so in spaces with many characters only characters that changed get re-validated
- Calculated item properties are now cached, helping in spaces with many characters and with overall performance as this is often queried for your character to determinate things such as if you are allowed to perform some actions and various effects like blindness
- Debug logs now have lower performance impact if debug logging is not enabled
- Queued calculations (such as checking validity of action buttons in Wardrobe) can now do several calculations at a time, if they are quick enough
```
> [CHANGE] Game logic performance optimizations

- pandora-client-web/src/components/wardrobe/views/characterModifiers/conditions/conditionItemOfAsset.tsx
- pandora-client-web/src/components/wardrobe/views/characterModifiers/conditions/conditionItemWithAttribute.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeAssetView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeItemView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitEditView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeSecondaryInventoryView.tsx
- pandora-client-web/src/components/wardrobe/wardrobeItemPreferences.tsx
- pandora-client-web/src/editor/components/layer/layerAutoMesh.tsx
- pandora-client-web/src/ui/tutorial/tutorials/wardrobeBody.tsx
- pandora-client-web/src/ui/tutorial/tutorials/wardrobeItems.tsx
- pandora-client-web/src/ui/tutorial/tutorials/wardrobeItemsAdvanced.tsx
_None_
```md
Fixes:
- Fixed some tutorials not being complete-able after recent asset name unification
```
> [FIX] Tutorials update after asset renaming
