- pandora-common/src/character/characterTypes.ts
This changes character id matching to recognize `c0` as a valid character id - it is id used by editor.
> [FIX] Fix editor crash when creating a new asset

- pandora-client-web/src/character/character.ts
- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
- pandora-client-web/src/components/chatroom/chatRoomDevice.tsx
- pandora-client-web/src/components/chatroom/chatRoomScene.tsx
- pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
- pandora-client-web/src/editor/graphics/character/appearanceEditor.ts
~~Depends on: #311 (reuses the refactor of background handling and blindness filters)~~
This PR fixes two problems:
- Player character graphics shouldn't be affected by blindness, but this wasn't the case while in a device, now they are not affected as intended
- Other characters should be affected when looking at them in wardrobe to avoid cheating
> [FIX] Fix blindness affecting player in a device and in wardrobe

- pandora-client-web/src/components/hoverElement/hoverElement.tsx
- pandora-client-web/src/editor/editorContextProvider.tsx
- pandora-client-web/src/index.tsx
This can be currently seen in wardrobe on drop elements that report the action isn't possible.
> [FIX] Prevent hover element from rendering under other elements

- pandora-client-web/src/components/chatroomSelect/chatroomSelect.tsx
- pandora-common/src/assets/state/roomState.ts
- pandora-common/src/chatroom/room.ts
- pandora-common/src/networking/connection.ts
- pandora-server-directory/src/room/room.ts
- pandora-server-shard/src/room/room.ts
This PR fixes (most) crashes in all three components when there is a room with invalid data being loaded. This brings the flow very close to how characters are currently handled. (with exception of Directory's state management, that will need few more tweaks, but right now errors that happen from race conditions there can be safely ignored as they result in valid state of everyone involved being unloaded and can be safely loaded again)
It also updates room inventory bundle to behave more like character bundle - dropping invalid items, and defaulting to default one if there is none present.
Another small change is in core, where instead of throwing string errors a proper error is thrown to get full stack in case of uncaught exception.
> [FIX] Fix shard crashing when loading room with invalid data

- pandora-client-web/src/components/Eula/privacyPolicy.tsx
- pandora-client-web/src/components/chatroom/commands.ts
- pandora-client-web/src/components/chatroom/contextMenus/characterContextMenu.tsx
- pandora-client-web/src/components/header/Header.tsx
- pandora-client-web/src/components/releationships/relationships.tsx
- pandora-client-web/src/components/wiki/pages/intro.tsx
Feedback was that the the mixture of character and account level functionality is confusing, especially the friend list feature as you are not becoming friends with the character you know and you send the friend request to but with an account name you do not know. The question was how your character can become friends with specific characters and if you cannot send DMs per character to support different RPs etc.
To make it clear that this feature is not to be seen as a de facto relationship feature like in a certain other plattform, I discussed with Jomshir to rename the friend list to contacts list to make it more neutral and OOC, which will hopefully make it clear that you will be able to become friends or any other type of relationship with a character later with a future feature.
I …
> [CHANGE] friend list renaming

- pandora-client-web/package.json
- pnpm-lock.yaml
This dependency seems to have been added during pnpm migration (#88), because tests were failing without it.
When I tested this after removing the dependency, it doesn't seem to be the case anymore. I'm not sure what exactly changed, as socket.io doesn't seem to have changed how it depends on engine.io, however we did have a major update of pnpm and some configuration changes for it, so that is most likely cause in my opinion.
> [CHORE] Remove unused `engine.io-client` dependency

- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/editor/components/bones/bones.tsx
- pandora-client-web/src/editor/components/layer/layer.tsx
- pandora-client-web/src/editor/parsing.ts
- pandora-client-web/src/graphics/appearanceConditionEvaluator.ts
- pandora-client-web/src/graphics/mirroring.ts
- pandora-common/src/assets/appearance.ts
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/appearanceLimit.ts
- pandora-common/src/assets/assetManager.ts
- pandora-common/src/assets/definitions.ts
- pandora-common/src/assets/graphics/graphics.ts
- pandora-common/src/assets/state/characterState.ts
- pandora-common/src/assets/state/globalState.ts
- pandora-common/src/networking/shard_directory.ts
- pandora-common/src/validation.ts
Adds new legs state enum:
```ts
export const LegsPoseSchema = z.enum(['standing', 'sitting', 'kneeling']);
export type LegsPose = z.infer<typeof LegsPoseSchema>;
```
add new atomic conditions for legs and view
fake bones are removed at the end, they are required to make it easier to create atomic commits and reduce the size of them
Draft until:
- ~~#325 is merged (since this will have some conflicts and I didn't include some changes due to that)~~
- ~~the respective assets repo PR is made~~
> [REFACTOR] enum for legs pose

- pandora-client-web/src/components/chatroom/contextMenus/characterContextMenu.tsx
- pandora-client-web/src/components/chatroomAdmin/chatroomAdmin.tsx
- pandora-client-web/src/components/header/Header.tsx
- pandora-client-web/src/components/releationships/relationships.scss
- pandora-client-web/src/components/releationships/relationships.tsx
- pandora-client-web/src/components/releationships/relationshipsContext.ts
- pandora-client-web/src/index.scss
- pandora-client-web/src/networking/socketio_directory_connector.ts
- pandora-client-web/src/styles/globalUtils.scss
This PR does following changes:
- Splits `relationships.tsx` file into this and context file, so UI can be changed without whole page reloading (no changes to the context code, except rename of one function)
- Cleanups style of contacts list by sorting columns differently and making some smaller
- Renames column "Created" to "Since" and only shows date instead of date and time
- Adds a green or empty dot next to "Online" or "Offline", respectively, for quicker orientation; also makes the Offline text into italics
> [CHANGE] Cleanup contacts list, add online indicator

- .github/workflows/pr.yml
This adds a workflow that auto-approves PRs from lead devs or renovate (so we can move to the "2-reviews" requirement while keeping 1-review for Lead devs and Renovate).
~~Not tested, as I don't have anywhere to actually test it.~~
Tested on personal repository.
> [DEV] Auto-approve for PRs from lead devs or Renovate

- .github/workflows/pr.yml
This fixies issue with auto-approves that appeared in #196.
Before this fix the login of person triggering the event was used to check - this meant that if, for example, lead dev added a label or changed PR name, then the approve would trigger.
This PR changes this to use login of person that authored the PR (hopefully, the docs aren't the best, but testing on personal repo makes it seem like that is the case)
Also fixes problem where concurrency could cause PR title check to fail.
> [DEV] Fix: Use PR author for checking

- .vscode/tasks.json
- pandora-client-web/package.json
- pandora-client-web/webpack.config.ts
This PR configures webpack to show messages about compilation starting and finishing to let VSCode properly detect state of compilation in the background task. This is necessary to avoid showing stale errors from previous compilation when they were fixed.
Also makes Webpack show progress in VSCode to be more interactive.
> [DEV] Improve webpack watch detection, show progress

- pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
Fixes bug introduced in #402.
During back view the X scale is multiplied by `-1`. This however requires also swapping direction of culling, as points suddenly form CW instead of CCW triangles. `GraphicsCharacter` did this automatically before.
Fixes this problem by moving the X inversion back to `GraphicsCharacter` instead of doing it on the outer container.
> [FIX] Fix character back view being broken

- .github/workflows/automation-autoapprove.yml
- .github/workflows/pr-lint.yml
GitHub's `concurrency` is quite broken in its current implementation: Instead of working as a lock and queuing any actions and running them in series, there can only be at most one running and one pending action. If new action enqueues any currently pending action is canceled.
This means that normally only the first and last job queued in quick succession runs, but those can be from different PRs.
This fix tries to avoid the race condition altogether by splitting the auto-approve into a separate workflow that only runs once on PR open.
> [DEV] Fix autoapprove job failing if run multiple times

- .github/workflows/automation-autoapprove.yml
Unfortunately `pull_request_target` CI cannot be tested differently than having it somewhere on `master`...
> [FIX] Hotfix: An important line got lost somewhere

- pandora-client-web/.eslintrc.json
- pandora-client-web/src/components/chatroom/chatInput.tsx
- pandora-client-web/src/components/chatroom/commands.ts
- pandora-client-web/src/components/chatroom/commandsProcessor.ts
- pandora-client-web/src/components/chatroom/contextMenus/characterContextMenu.tsx
- pandora-client-web/src/components/common/tabs/tabs.tsx
- pandora-client-web/src/components/dialog/dialog.tsx
- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/components/directMessages/directMessages.scss
- pandora-client-web/src/components/directMessages/directMessages.tsx
- pandora-client-web/src/components/management/betaKeys/betaKeys.tsx
- pandora-client-web/src/components/management/shards/shards.tsx
- pandora-client-web/src/components/releationships/relationships.tsx
- pandora-client-web/src/components/releationships/relationshipsContext.ts
- pandora-client-web/src/components/settings/accountSettings.tsx
- pandora-client-web/src/editor/components/asset/asset.tsx
- pandora-client-web/src/networking/directMessageManager.ts
- pandora-client-web/src/routing/Routes.tsx
- pandora-common/src/networking/directory_client.ts
> [FEATURE] Friends UI Navigation

- pandora-client-web/src/components/wardrobe/views/wardrobeExpressionsView.tsx
- pandora-client-web/src/graphics/graphicsLayer.tsx
- pandora-client-web/src/graphics/graphicsMaskLayer.ts
Also avoids crashing when the mask is set to empty (which was why the original code was written in the way it was).
Adds a small fix to fix React's warning about duplicate key in wardrobe expressions, when two items have modules with same name.
> [FIX] Fix alphamask change sometimes not trigerring redraw

- pandora-server-directory/src/lifecycle.ts
- pandora-server-directory/src/services/discord/discordBot.ts
Prevents the throttle from being invoked (and such creating 10 minute timer that isn't stopped), allowing Directory to shut down cleanly even when not using the bot.
Also fixes misleading progress message.
> [FIX] Fix DiscordBot hanging shutdown when not in use

- .vscode/launch.json
- pandora-client-web/webpack.config.ts
The Firefox debugger doesn't like it when exception is thrown in a file that has _no_ physical counterpart on the disk - this happens for example when dev server forces full reload when it can't do HMR.
This change makes even development version of Webpack emit the files and uses inlined source maps to allow proper resolution.
> [DEV] Fix firefox debugger breaking when reload happens

- pandora-client-web/src/components/wiki/pages/greeting.tsx
- pandora-client-web/src/components/wiki/pages/history.tsx
- pandora-client-web/src/components/wiki/pages/intro.tsx
- pandora-client-web/src/components/wiki/wiki.tsx
This page can also be linked on Discord when users ask about how Pandora came to be and who is involved.
It should also answer potentially frequently asked questions in advance.
> [ADD] adds a new wiki tab with the history of pandora

- pandora-client-web/src/common/useEvent.ts
- pandora-client-web/src/components/chatroom/contextMenus/deviceContextMenu.tsx
- pandora-client-web/src/components/contextMenu/contextMenu.scss
- pandora-client-web/src/components/dialog/dialog.tsx
- pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemRoomDevice.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
- pandora-client-web/src/components/wardrobe/wardrobe.scss
- pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
- pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
- pandora-client-web/src/components/wardrobe/wardrobeUtils.ts
- pandora-client-web/src/persistentToast.ts
- pandora-client-web/src/styles/globalUtils.scss
Makes following changes:
- Updates "confirm" dialog to accept more complex body and uses simple bold text instead of h1
- Adds confirmation dialog before performing action you can't undo
- Right now detects action that changed `blockHands` effect on `player` from `false` to `true`
- Improves room device menu
- Buttons for invalid actions always show and are instead stricken through
- Character button have background color based on their label color
- Clicking invalid button displays toast with reason for the invalidity
- Storing room device prompts for confirmation
> [FEATURE] Add confirmation for actions you can't undo

- pandora-client-web/package.json
- pandora-tests/test/eula.test.ts
- pandora-tests/test/utils/helpers.ts
- pandora-tests/test/wiki.test.ts
- pnpm-lock.yaml
Tracking issue for upstream: https://github.com/remix-run/react-router/issues/11052
> [FIX] Add Wiki tests and downgrade react-router to avoid latest regression for nested routing

- pandora-common/src/assets/item.ts
- pandora-common/src/assets/roomDeviceProperties.ts
Adds same state flags support as normal items have to room device modules - allowing room devices to limit which internal states are valid.
> [ADD] State flag support for room devices

- pandora-client-web/src/common/downloadHelper.ts
- pandora-client-web/src/components/exportImport/exportDialog.tsx
- pandora-client-web/src/components/input/numberInput.tsx
- pandora-client-web/src/components/settings/interfaceSettings.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeAssetView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeItemView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitEditView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeRoomInventoryView.tsx
- pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
- pandora-client-web/src/editor/assets/assetManager.ts
- pandora-client-web/src/editor/components/assets/assets.tsx
- pandora-client-web/src/editor/components/previewCutter/previewCutter.scss
- pandora-client-web/src/editor/components/previewCutter/previewCutter.tsx
- pandora-client-web/src/editor/graphics/character/appearanceEditor.ts
- pandora-client-web/src/editor/graphics/editorScene.tsx
- pandora-client-web/src/editor/graphics/export/imageExporter.ts
- pandora-client-web/src/editor/graphics/layer/resultLayer.tsx
- pandora-common/src/assets/definitions.ts
- pandora-common/src/networking/directory_client.ts
- add `preview?: string | null` to asset definition (allow undefined until all assets have this property defined)
- add preview cutter for the result layer (Preview tab), and controls on Items tab
> [FEATURE] preview cutter

- .vscode/settings.json
- pandora-client-web/src/assets/appearanceValidation.ts
- pandora-client-web/src/components/chatroom/chatRoomDevice.tsx
- pandora-client-web/src/components/chatroom/chatRoomScene.tsx
- pandora-client-web/src/components/chatroom/chatroomControls.tsx
- pandora-client-web/src/components/chatroom/contextMenus/deviceContextMenu.tsx
- pandora-client-web/src/components/gameContext/chatRoomContextProvider.tsx
- pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemRoomDevice.tsx
- pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
- pandora-client-web/src/components/wardrobe/wardrobeUtils.ts
- pandora-client-web/src/editor/components/wardrobe/wardrobe.tsx
- pandora-client-web/src/graphics/movementHelper.tsx
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/assets/effects.ts
- pandora-common/src/character/restrictionsManager.ts
- pandora-common/src/chatroom/room.ts
- pandora-server-shard/src/room/room.ts
This PR introduces following changes:
- Room device deployment and movement now requires being an admin
- Room device deployment and movement now requires holding room construction tools (item provided in asset repo PR)
- The confirmation prompt for storing a device is now using the standardized action confirmation dialog
- Reworked how moving device works
- Reworked the interaction helper overlay
> [CHANGE] Room devices setup rework

- contributor-licence-agreement.md
This PR adds a CLA - Contributor License Agreement, which applies to any contribution made via GitHub (I will be making a PR template later that also states this explicitly).
The proposed CLA is based on the Apache Foundation individuals CLA; rewritten into markdown from the original PDF:
[https://apache.org/licenses/icla.pdf](https://apache.org/licenses/icla.pdf)
The reason for adding the CLA is the following: We already encountered a situation where it is beneficial for us to change the license on our code. So far it isn't much of a problem as we have few past contributors, but once outside people contribute it might become problematic to get agreement to update the license if necessary in the future.
At the moment of addition of the CLA the repository contains code from the following …
> [DEV] Contributor license agreement

- pandora-server-directory/src/account/character.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/room/room.ts
- pandora-server-directory/src/room/roomManager.ts
- pandora-server-directory/test/room/room.test.ts
- pandora-server-directory/test/room/roomManager.test.ts
This reworks how deletion works from being eager to delete the room, to simply marking it as "pending deletion".
This kicks everyone inside, unloads it from the current shard and then deletes it from the database. The room is however then not immediately unloaded to allow any lingering references to be removed (such as characters pending join during that time) before unloading the room cleanly.
> [FIX] Fix room deletion (last owner abandoning ownership)

- pandora-common/src/assets/item.ts
- pandora-common/src/assets/state/characterState.ts
Puts the room device link into an invalid state instead of deleting it when it is not valid.
This is important because during some actions the link can become temporarily invalid and later restored. After this change it will effectively be no change for the link instead of being deleted during that.
> [FIX] Do not remove room device link unless revalidating

- pandora-client-web/src/components/gameContext/directoryConnectorContextProvider.tsx
- pandora-client-web/src/graphics/graphicsCharacter.tsx
- pandora-client-web/src/graphics/graphicsSceneRenderer.tsx
- pandora-client-web/src/graphics/graphicsSuspense/graphicsSuspense.tsx
Fixes several crashes in editor.
Improves graphics suspense:
- Both container updates and loading progress updates happen synchronously and outside React now
- This avoids previous error in editor / when using custom texture getter
- Adds a grace period before showing progress again after being ready
> [FIX] Fixes and improvements for graphics suspense and editor

- pandora-client-web/src/components/login/forms/registrationForm.tsx
- pandora-client-web/src/components/login/forms/resetPasswordForm.tsx
- pandora-client-web/test/components/login/forms/registrationForm.test.tsx
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/validation.ts
Reasoning:
~~Change 1. Give warning to users to not use a sensitive username since they think it is hidden~~ EDIT: seems with the activities around using `displayName` everywhere, this is no longer needed, so I reverted this change again
Change 2. Prevent bad actors from undoing lots of work by changing room device colors randomly without leaving a trace even in the chat
Change 3. We still should force users to select a strong enough password, despite our account security measures. Yes, this will lead to serious bad actors focusing on trying passwords with a length of 8-10 characters mainly, but overall it still improves the security situation on average, I think.
> [ADD] coloring permission of devices and minimum account password length

- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/components/directMessages/directMessages.tsx
- pandora-client-web/src/networking/directMessageManager.ts
- pandora-client-web/test/mocks/networking/mockDirectoryConnector.ts
- pandora-common/src/networking/client_directory.ts
- pandora-common/src/networking/directory_client.ts
- pandora-server-directory/src/account/account.ts
- pandora-server-directory/src/account/accountDirectMessages.ts
- pandora-server-directory/src/account/accountSecure.ts
- pandora-server-directory/src/networking/manager_client.ts
prevent direct update of the crypto key after its first creation, as it was never an intended behavior
change DMs to refer to the upcoming `displayName` of the account instead of the username
> [CHANGE] crypto key should not be changed directly

- pandora-client-web/src/components/chatroom/commandsHelpers.ts
- pandora-client-web/src/components/chatroom/commandsProcessor.ts
Since we seem to allow full numerical names as character names, ~~there is a bug that makes such characters impossible to whisper to with the according command~~.
While I was there, I also improved the character ID parsing, so that it also allows usage of the actual character ID with a lead "c", as this part could be very confusing to users, that they have to use the character ID without the "c", which would make it look like the account ID.
**By the way, I am not sure it is a good idea to allow numbers in character and display names. It just feels like an invitation to make weird immersion breaking character names. Thoughts?**
> [FIX] improved CommandSelectorCharacter ID parsing

- pandora-client-web/src/components/common/colorInput/colorInput.scss
- pandora-client-web/src/components/common/colorInput/colorInput.tsx
Fixes the mouse position calculation inside the square so the circle is no longer slightly off
code is based on:
https://sci-hub.se/10.1016/j.compeleceng.2015.08.005
Note:
The linear gradient expands outside the range of the possible slider position, which causes some inaccuracy. 
This is mostly noticeable for the HUE slider.
This was an issue before the change; I will address it later in PR.
> [FIX] use integer-based accurate conversion for RGB/HSV

- pandora-client-web/src/common/clipboard.ts
- pandora-client-web/src/components/common/tabs/tabs.tsx
- pandora-client-web/src/components/error/errorReport.ts
- pandora-client-web/src/components/error/forwardingErrorBoundary.tsx
- pandora-client-web/src/components/error/localErrorBoundary.scss
- pandora-client-web/src/components/error/localErrorBoundary.tsx
- pandora-client-web/src/components/error/rootErrorBoundary.tsx
- pandora-client-web/src/components/exportImport/exportDialog.tsx
- pandora-client-web/src/graphics/graphicsScene.tsx
- pandora-client-web/src/graphics/graphicsSceneRenderer.tsx
This PR adds various error handling to the client so not all errors make it go nuclear anymore, namely:
- Adds "local" error boundary that shows placeholder element with ability to open the error report
- Adds "forwarding" error boundary that shows nothing and calls a callback when error happens (used to get errors out of Pixi's fiber into DOM context)
- Wraps all tabs in a local error boundary automatically
- Wraps all graphic scenes in a local error boundary
- Forwards errors from Pixi's fiber into the outer one
> [FEATURE] Localized error boundaries for client

- pandora-client-web/src/assets/assetManager.ts
- pandora-client-web/src/components/gameContext/directoryConnectorContextProvider.tsx
- pandora-client-web/src/config/searchArgs.ts
- pandora-client-web/src/editor/index.tsx
- pandora-client-web/src/index.tsx
- pandora-client-web/src/networking/socketio_shard_connector.ts
- pandora-server-shard/src/networking/connection_client.ts
Adds ability to specify multiple URLs for server connections or asset sources. This is to support fallback URLs if Cloudflare is having a bad day (which seems to be fairly often recently). There is no automatic failover mechanism - the index of server/assets url needs to be specified via URL search argument, such as:
```
https://fallback.project-pandora.com/?serverindex=1
```
The argument is remembered in session storage so it is not accidentally lost on F5 or similar actions.
> [FEATURE] Allow specifying multiple URLs for server connection

- pandora-client-web/src/common/userInteraction/inputAutofocus.ts
- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeAssetView.tsx
- pandora-client-web/src/components/wardrobe/wardrobeItemPreferences.tsx
- pandora-client-web/src/ui/components/chat/chatInput.tsx
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
Firefox needs the input to be focused before `keypress` fires. This PR mainly changes the hook to work on `keydown` and unifies the behavior for all such inputs.
> [FIX] Fix text input autofocus not working on Firefox

- pandora-client-web/src/networking/directoryConnector.ts
- pandora-client-web/src/networking/socketio_directory_connector.ts
- pandora-client-web/src/routing/Routes.tsx
- pandora-client-web/test/mocks/networking/mockDirectoryConnector.ts
- pandora-server-directory/src/account/character.ts
- pandora-server-directory/src/networking/manager_client.ts
This PR:
- Fixes problem that the screen could get stuck randomly
- Fixes problem that the screen would get stuck if another client took over the character
- Fixes problem that the first client would try to take back character taken over by different client on refresh
- Fixes a race condition in the directory server around client disconnecting in the middle of character connection
To do that it:
- Removes the explicit connection state; the dialog instead uses state collected from directory and shard connectors to display it
- Removes listing of characters; the id is simply used to try to connect. This removes the behavior of auto-selecting a character in-creation if it is the only character the player has, but I don't think that is a problem.
- Clears the last character id if the connect …
> [REFACTOR] Simplify character autoconnect logic

- pandora-client-web/src/components/wiki/pages/greeting.tsx
- pandora-client-web/src/components/wiki/pages/history.tsx
- pandora-client-web/src/components/wiki/pages/intro.tsx
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.scss
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.tsx
Separates the space config view into two tabs:
- General for configuring the space itself
- Visitor Management for for handling permission lists and invites
Also updates the wiki a little bit.
> [CHANGE] space config UI and wiki updates

- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
- pandora-common/src/space/space.ts
- pandora-server-directory/src/config.ts
- pandora-server-directory/src/database/mongoDb.ts
Adds a code for full database migration. This code walks through every single document in all collections and runs it through a supplied Zod schema, updating the document to match (both changed and deleted properties, unlike our current on-the-fly migrations).
The migration is disabled by default and can be activated either in dry-run mode (where the changes are not actually committed to the database) or for actual migration.
These are triggered with env configuration `DATABASE_MIGRATION=dry-run` and `DATABASE_MIGRATION=migrate` respectively.
Note that some collections currently don't have a Zod schema. Those are walked through and ignored. (TODOs have been added)
> [FEATURE] Full database migration

- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.tsx
This prevents the "Joining space" toast from getting stuck.
> [FIX] Update spaces search progress even after unmount

- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/components/gameContext/directoryConnectorContextProvider.tsx
- pandora-client-web/src/components/settings/accountSettings.tsx
- pandora-client-web/src/components/settings/helpers/accountSettings.tsx
- pandora-client-web/src/components/settings/helpers/settingsInputs.tsx
- pandora-client-web/src/components/settings/interfaceSettings.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitView.tsx
- pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
- pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
- pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
- pandora-client-web/src/graphics/graphicsSettings.tsx
- pandora-client-web/src/graphics/room/roomCharacter.tsx
- pandora-client-web/src/graphics/room/roomScene.tsx
- pandora-client-web/src/ui/components/chat/chat.tsx
- pandora-client-web/src/ui/screens/room/room.tsx
- pandora-common/src/account/index.ts
- pandora-common/src/account/settings.ts
- pandora-common/src/networking/client_directory.ts
- pandora-common/src/networking/directory_client.ts
- pandora-server-directory/src/account/account.ts
- pandora-server-directory/src/account/accountContacts.ts
- pandora-server-directory/src/account/accountDirectMessages.ts
- pandora-server-directory/src/database/databaseProvider.ts
- pandora-server-directory/src/database/databaseStructure.ts
- pandora-server-directory/src/networking/manager_client.ts
This PR changes our settings saving structure to be sparse - defaults are not present in the saved data, but instead used when setting is accessed.
Changing setting back to default value manually will still save the default value explicitly.
This combination will allow us to change defaults for settings, such that people that never touched it will get the new default, but people who modified it manually with keep their value (even if their value was previous default).
Resetting the setting using reset button will delete it from settings storage, causing user to potentially get new default value if it changes.
Also reworks the settings UI slightly:
- Refactors much of the code to be more generic, making it easier to add more settings in the future
- Adds reset button to most settings. This …
> [FEATURE] Sparse settings

- .github/workflows/ci.yml
- .gitignore
- .hooks/coverage-collect.cjs
- .hooks/coverage-collect.js
- .hooks/postinstall.cjs
- package.json
- pandora-client-web/jest.config.js
- pandora-client-web/webpack.config.ts
- pandora-common/jest.config.js
- pandora-server-directory/jest.config.js
- pandora-server-shard/jest.config.js
- pandora-tests/.gitignore
- pandora-tests/package.json
- pandora-tests/test/_setup/config.ts
- pandora-tests/test/_setup/global_setup.ts
- pandora-tests/test/directory_connection.test.ts
- pandora-tests/test/eula.test.ts
- pandora-tests/test/load.test.ts
- pandora-tests/test/utils/coverage.ts
- pandora-tests/test/utils/helpers.ts
- pandora-tests/test/utils/server.ts
- pandora-tests/test/wiki.test.ts
- pnpm-lock.yaml
This PR adds coverage collection for E2E tests (both client and server), and adds few more bits to combine coverage from individual and E2E tests into a single report.
Locally this can be obtained by running `pnpm run ci` in the workspace root (will take a few minutes).
In CI the coverage is collected but not used yet. In the future we could easily setup something like CodeCov to get coverage diff for each PR.
There is a slight slowdown involved in the coverage collection, but I would say relatively minor one.
The coverage collection for client (+common) during E2E testing was easy, but getting it transformed into a reasonable format was not. It is a bit inaccurate due to the minimization the client build does despite the existence of sourcemaps. It took me several hours to get it to …
> [DEV] Tests coverage collection

- pandora-common/src/account/settings.ts
- pandora-common/src/inputLimits.ts
- pandora-server-directory/src/account/account.ts
- pandora-server-directory/src/account/accountContacts.ts
- pandora-server-directory/src/config.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/spaces/spaceManager.ts
- pandora-server-shard/src/spaces/spaceManager.ts
This PR bundles a few smaller cleanups:
- Metric ids are renamed to use spaces naming
- Old socket message guards were removed, as we use Zod everywhere
- DM preference value was changed to use `space` instead of `room` (do we actually have GUI for setting this?)
- Old character and space ownership limits were moved to the new common limits declarations instead of being env-dependent (we didn't even have them in env config template)
> [DEV] Small cleanup after spaces changes

- pandora-client-web/src/components/Eula/privacyPolicy.tsx
- pandora-common/src/inputLimits.ts
Updates the privacy policy to revision 2 after exactly one year!
Tries to implement (2) of https://github.com/Project-Pandora-Game/pandora/issues/559
and https://github.com/Project-Pandora-Game/pandora/issues/578
Questions I have:
1. Is it enough to update the privacy policy or do we need some terms of use that state this?
2. Do we need some automatic way that deletes messages when they are older than 1 year? Doing it manually sounds very error prone and tedious. I feel we should do that before we update the privacy policy with this PR.
> [CHANGE] update privacy policy

- pandora-client-web/src/components/directMessage/directMessage.scss
- pandora-client-web/src/ui/screens/room/room.scss
Adds a clip to the chat messages so a message can't overflow itself. The full message is still shown on hover in case something gets clipped unintentionally or admin just wants to see what message's author tried to do.
A bit stricter "hidden" is used as backup for iOS devices that still might not support clip.
> [FIX] Prevent Zalgo text

- pandora-server-directory/src/database/databaseStructure.ts
It appears in the past we used `null` for `edited` instead of having it optional as it is now. This causes the edited time to be dropped when it is invalid.
> [FIX] Drop invalid direct message edit time

- pandora-client-web/src/components/wiki/pages/characters.tsx
- pandora-client-web/src/components/wiki/pages/greeting.tsx
- pandora-client-web/src/components/wiki/pages/intro.tsx
- pandora-client-web/src/components/wiki/pages/items.tsx
- pandora-client-web/src/components/wiki/pages/new.tsx
- pandora-client-web/src/components/wiki/pages/spaces.tsx
- pandora-client-web/src/components/wiki/wiki.tsx
- pandora-client-web/src/styles/_constants.scss
- pandora-client-web/src/ui/screens/room/roomControls.tsx
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
- pandora-common/src/character/speech.ts
- pandora-common/src/chat/chat.ts
This PR contains:
- a new tab in the wiki with a new user guide and embedding it in other intro pages
- improvements and small updates to most other wiki pages
- few small text improvements in the space admin view, the ooc command description, and the personal space help text
- minor change of the garbling method to be slightly more accurate
> [CHANGE] new user guide, wiki improvements, and garbling improvements

- pandora-client-web/package.json
- pnpm-lock.yaml
`@testing-library/jest-dom` now provides its own type definitions, so the external typings are no longer needed.
> [CHORE] Drop `@types/testing-library__jest-dom`

- pandora-client-web/src/components/wiki/pages/characters.tsx
- pandora-client-web/src/components/wiki/pages/history.tsx
- pandora-client-web/src/components/wiki/pages/spaces.tsx
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
- pandora-server-directory/src/config.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/spaces/spaceManager.ts
This PR hides the option to create a space in development mode if you are not having the role of a developer or higher.
Following things need improvement, which are beyond my level of knowledge:
- Make the directory reject a space creation if it includes the effect "development" but the creator is not having the developer role
- Make it so that the space background image or solid color has a large (slightly transparent?) text overlayed "Development mode"
> [CHANGE] gate development mode and document space effects

- pandora-server-directory/src/account/account.ts
- pandora-server-directory/src/account/accountRoles.ts
- pandora-server-directory/src/account/actorIdentity.ts
- pandora-server-directory/src/account/actorPandora.ts
- pandora-server-directory/src/config.ts
- pandora-server-directory/src/database/databaseStructure.ts
- pandora-server-directory/src/database/mongoDb.ts
- pandora-server-directory/src/index.ts
- pandora-server-directory/src/lifecycle.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/services/betaRegistration/betaRegistration.ts
- pandora-server-directory/src/services/discord/commands/_common.ts
- pandora-server-directory/src/services/discord/commands/ping.ts
- pandora-server-directory/src/services/discord/commands/registration.ts
- pandora-server-directory/src/services/discord/discordBot.ts
- pandora-server-directory/src/shard/betaKeyStore.ts
- pandora-server-directory/src/shard/tokenStoreBase.ts
This adds mechanism for Discord commands, and flow to create a beta registration prompt, let users register for beta, and finally automatic sending of beta invites where each user gets their own single-use beta key via DM. Also handles role assignment for each of these actions.
For now I lazily store all beta registrations in single config document (beta keys are done this way too after all). If we get over about 131 thousand registrations it will need a rework, but oh well.
> [FEATURE] Discord beta registrations and invites

- pandora-client-web/src/components/gameContext/gameStateContextProvider.tsx
- pandora-client-web/src/editor/components/wardrobe/wardrobe.tsx
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/space/space.ts
- pandora-server-shard/src/spaces/space.ts
This change all previously created development spaces as they will no longer have the bypass safemode cooldown feature
New spaces will need to enable this at creation time
> [FEATURE] flag for safemode cooldown bypass

- pandora-server-directory/src/services/betaRegistration/betaRegistration.ts
- pandora-server-directory/src/services/discord/discordBot.ts
Adds three Prometheus metrics:
- Two gauges for beta registrations (total and pending)
- One counter for processed Discord bot commands
> [ADD] Metrics for beta registrations

- pandora-server-directory/src/database/mongoDb.ts
- pandora-server-directory/src/lifecycle.ts
The way terminal works is, that if user does Ctrl+C in the terminal, the signal is sent to the whole _process group_.
This means that Mongo was receiving the signal too, and shutting down before Pandora itself had chance to.
By detaching it this doesn't happen.
Also note, that the `mongodb-memory-server` has a killer script that periodically checks if parent process is still running, so the database will get killed even if the main process dies on the spot, even if detached.
> [FIX] Start database process detached to prevent killing it too early

- pandora-common/src/utility.ts
- pandora-server-directory/src/database/databaseStructure.ts
- pandora-server-directory/src/services/betaRegistration/betaRegistration.ts
- pandora-server-directory/src/services/discord/commands/registration.ts
Adds an admin command to prune users registered for beta (based on guild membership and missing roles).
Also makes the code generally more robust by differentiating user with generated beta key and user for which Discord confirmed that they actually received the key - allowing us to easily resend the keys if there is a problem with mass-sending.
Also increased the delay to take 1.5 seconds per invited user, so we hopefully don't run into Discord's DM rate limiting.
> [ADD] Beta registration pruning

- pandora-client-web/src/ui/screens/spaceJoin/spaceJoin.tsx
- pandora-common/src/space/space.ts
- pandora-server-directory/src/database/databaseStructure.ts
- pandora-server-directory/src/database/dbHelper.ts
- pandora-server-directory/src/database/mockDb.ts
- pandora-server-directory/src/database/mongoDb.ts
- pandora-server-directory/src/database/validatedCollection.ts
- pandora-server-directory/test/database/db.ts
- pandora-server-directory/test/spaces/spaceManager.test.ts
- pandora-server-shard/src/database/mongoDb.ts
This PR adds several migrations to the database for old data (we really want to migrate before beta to be safe). All added migrations are idempotent.
- Store account/character id counters explicitly in a config document instead of generating them by scraping account and character collections
- Change the character collection to use string CharacterId instead of translating it to number and back
- Rename `chatrooms` collection to `spaces`
- Change space id format from r/abc to s/abc
- Minor cleanup of no longer needed utilities after these migrations
> [CHANGE] Several database migrations

- pandora-client-web/src/components/settings/permissionsSettings.tsx
- pandora-client-web/src/components/wiki/pages/new.tsx
- pandora-client-web/src/components/wiki/pages/spaces.tsx
- pandora-common/src/gameLogic/interactions/_interactionConfig.ts
- pandora-common/src/networking/client_directory.ts
- pandora-server-directory/src/account/character.ts
- pandora-server-directory/src/networking/manager_client.ts
- pandora-server-directory/src/spaces/space.ts
Renamed a string value, because as a user, it is very confusing when you try to join a space and get an error toast about `errFull`.
These messages were clearly not made end user friendly, but I at least wanted to make it a little bit better by calling it `spaceFull` instead of `errFull`.
Also improves the permission dialog clarity, as it was reported to be an issue and I can see why.
> [CHANGE] renamed errFull to spaceFull and improved permission dialog

- pandora-client-web/src/components/common/colorInput/colorInput.tsx
capture felt the best solution, this slightly change the behavior dragging the pointer out will still continue the change (I feel this is a bit better)
tried adding `onPointerOut` but it wasn't stable so capture is over all the better
(tested with multiple color inputs at the same time could not get it to stuck or broken in any way)
> [FIX] color input mouse up should be handled even outside

- pandora-server-shard/src/spaces/space.ts
fixes #654
add `satisfies` to prevent further errors
test:
> [FIX] directory action message target property

- pandora-client-web/src/components/common/button/button.scss
Fixes a regression introduced in #629, which pushed some buttons (most notably those on whispering/chat mode indicator) to a new line instead of keeping them in-line.
> [FIX] Fix buttons getting pushed to new lines

- pandora-client-web/src/components/settings/helpers/settingsInputs.tsx
- pandora-client-web/src/graphics/graphicsSettings.tsx
Changes the default setting for alphamasks to disabled, and adds explanation to the settings page what masks are and why we chose to disable them by default.
> [CHANGE] Disable alphamasks by default

- pandora-client-web/src/ui/components/chat/chat.tsx
Fixes #683 
I'm not sure _at all_ what I'm doing here, so do let me know if there is a better way or place to do this, I'm slowly picking my way around this codebase. This should implement the rendering of said messages only on receiving on the client, and only for `'s`
- Is this the right place for this formatting?
- Are there other situations in which the space should be elided? (Right now it's only messages prefixed with precisely `'s`)
- All of `*'s thing` and `* 's thing`, and `/me 's thing` produce `Name's thing` in chat, however note that `/me's` is invalid (as it fails to parse as a command). Intentional?
Testing various weird chat messages (including those with bold/italic, and multiline emote / non-emote parts all seems to be working as intended (although that's just the chat …
> [FIX] Don't insert a space for `/me` messages that start with `'s`

- pandora-client-web/src/components/directMessage/directMessage.scss
- pandora-client-web/src/components/directMessage/directMessage.tsx
fixes #682 
It appears Chrome prefers squishing flex children over scrolling under some specific conditions, involving the children having overflow hidden. This can cause current styling of DMs to squish messages when there are more than fit on a screen.
This PR updates the DM rendering implementation to use the same layout as chat is:
- A root bounding element with `relative` position - used for correctly positioning the `/` commands help overlay
- A `Scrollable` element that adds the scrollbar if the content gets bigger than it
- A single containing flex (in this case `Column`) for all the messages. It is important that this element is different than the one adding scrollbar to avoid the bug - it must be nested inside the scrollable element.
- The actual messages
> [FIX] Fix Direct messages getting squished on Chrome

- pandora-client-web/src/components/common/colorInput/colorInput.tsx
- pandora-client-web/src/components/settings/accountSettings.tsx
- pandora-client-web/src/components/settings/characterSettings.tsx
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
Closes #669 
This changes the input style for the basic `ColorInput` component to use the internal `ColorEditor` created for the `ColorInputRGBA` component. Because of this `ColorInput` has a new parameter required `title` which was retroactively included in the 3 locations the component was already used. 
Two magic numbers for representing max alpha inside the `colorinput.tsx` file were also converted to use the static global variable `Color.maxAlpha` instead of a hardcoded `255` like all other references in the file.
I chose to keep the `ColorInput` component instead of combining and converting them all into `ColorInputRGBA` across all use cases as I feel there could be good semantic reasons for having both as not all color fields should support alpha channels and it might become less …
> [CHANGE] Standardize ColorInput Component

- pandora-client-web/src/components/login/forms/resendVerificationAdvancedForm.tsx
- pandora-client-web/src/components/login/forms/resendVerificationForm.tsx
- pandora-client-web/src/networking/account_manager.ts
- pandora-client-web/src/routing/authRoutingData.ts
- pandora-common/src/networking/client_directory.ts
- pandora-server-directory/src/account/accountSecure.ts
- pandora-server-directory/src/config.ts
- pandora-server-directory/src/database/databaseProvider.ts
- pandora-server-directory/src/database/mockDb.ts
- pandora-server-directory/src/database/mongoDb.ts
- pandora-server-directory/src/networking/manager_client.ts
Add new form that requires username, password and email, instead of `maybeSent` user gets a detailed result if the email was incorrect
Optional checkbox to override the current account's email address
tested it locally just not quite sure if the UI texts are the best
> [FEATURE] change email for not activated accounts

- pandora-client-web/src/components/profileScreens/profileScreens.scss
The new color scheme is closer to the one used in other places e.g. chat and allows for easier distinguishing of edit and display mode.
__This is a change based on a conversation on https://github.com/Project-Pandora-Game/pandora/pull/694 that did not make it into  that pullrequest before merge__
> [CHANGE] Change color scheme of profile editor

- pandora-client-web/package.json
- pandora-client-web/src/components/common/colorInput/colorInput.tsx
- pnpm-lock.yaml
Do best effort to parse RGBA color on paste from:
- `RGB[A]`
- `#RGB[A]`
- `RRGGBB[AA]`
- `#RRGGBB[AA]`
- `rgb[a](R, G, B[, A])`
- `rgb(R G B[ / A])`
- `R:10 G:20 B:30`
- `(R10 / G20 / B30)`
- `[10, 20, 20]`
- `10,20,20`
- `0x00ff00`
Expandable to other color spaces if converter functions added in the future
> [FEATURE] better parse when pasting color values

- pandora-client-web/src/components/common/colorInput/colorInput.scss
- pandora-client-web/src/components/common/colorInput/colorInput.tsx
- pandora-client-web/src/components/dialog/dialog.scss
- pandora-client-web/src/components/dialog/dialog.tsx
Fixes #709 
When using mobile devices due to the way event propagation works and the lack of precision of how touch events are handled, the drag handling event always took precedence over the click even for closing the pop-up dialogs when using mobile devices as the two layers overlapped one another. Because of this I split the header into a two part flex with them handling their own events independently with the dragable portion taking a bulk of the header but no longer overlapping with the close button. (Because of this the title is currently left-aligned as well instead of trying to handle relative positioning to center it once more)
Converted the `<input type=color>` tag to a normal button to remove weird mobile event handling that was not preventing the default action from performing …
> [FIX] Color Input Mobile Compatability Improvements

- pandora-client-web/src/components/wardrobe/views/wardrobeItemView.tsx
- pandora-client-web/src/components/wardrobe/wardrobe.scss
- pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
- pandora-client-web/src/components/wardrobe/wardrobeItems.tsx
- pandora-client-web/src/components/wardrobe/wardrobeTypes.ts
- pandora-client-web/src/editor/components/wardrobe/wardrobe.tsx
- pandora-client-web/src/graphics/room/contextMenus/deviceContextMenu.tsx
This adds a shortcut from room devices' context menus to their menus in the room inventory view.
It is fully working as far as I know, but this is my first contribution to pandora and first time working with react, so there are a few design decisions and technical points I'm unsure of and I'd like to get opinions on:
**Design decision:**
- I turned the menu's header with the device name into the button to reach the inventory in order to save space, but maybe you'd prefer having a different button lower in the menu?
**Technical points:**
- Is the location state the right tool to pass the information to the inventory page? Or would it be better to use something else, e.g an optional route parameter.
- If so, is it the right way to clear the location state after use?
- I wanted the list of …
> [ADD] a shortcut from the device context menu to the inventory view

- pandora-client-web/.eslintrc.json
- pandora-client-web/src/ui/screens/spaceConfiguration/spaceConfiguration.tsx
- pandora-client-web/test/tsconfig.json
- pandora-client-web/test/tsconfig.setup.json
- pandora-common/src/chat/chatActions.ts
- pandora-common/src/networking/shard_directory.ts
- pandora-common/src/space/room.ts
- pandora-common/src/space/space.ts
- pandora-server-directory/src/networking/manager_shard.ts
- pandora-server-directory/src/spaces/space.ts
- pandora-server-directory/test/spaces/testData.ts
- pandora-server-shard/src/character/character.ts
- pandora-server-shard/src/spaces/personalSpace.ts
- pandora-server-shard/src/spaces/publicSpace.ts
- pandora-server-shard/src/spaces/space.ts
Adds ability to configure automatic kick of offline characters.
The scan for offline characters happens regularly by Shard and checks if character has been offline for X minutes before requesting Directory to kick it. If the request fails for whatever reason, it will be re-attempted during the next cycle.
Also has an option to ignore Owners/Admins/VIPs of a space.
Additionally increased the randomness of initial position generation 5-fold.
> [FEATURE] Autokick of ghost characters

- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/character/restrictionTypes.ts
- pandora-common/src/character/restrictionsManager.ts
Adds a new item interaction type that is used exclusively for when entering or leaving a room device slot.
Fixes #678
> [CHANGE] Do not require hands usage for entering and leaving room devices

- pandora-client-web/src/components/directMessage/directMessage.tsx
- pandora-client-web/src/crypto/symmetric.ts
- pandora-client-web/src/networking/directMessageManager.ts
Adds a few assets with more helpful error messages, removes saving `crypto.subtle` in a local variable, and adds a log of the full error when send crashes.
This (most likely) won't fix the crashes, but will at least allow us to debug them more.
Ref: #703
> [CHANGE] Improve robustness of DM encryption checks

- pandora-client-web/src/components/profileScreens/profileScreens.scss
- pandora-client-web/src/editor/index.tsx
- pandora-client-web/src/index.tsx
- pandora-client-web/src/persistentToast.ts
- pandora-client-web/src/styles/_constants.scss
- pandora-client-web/src/ui/screens/room/room.scss
- pandora-tests/test/wiki.test.ts
Fixes https://github.com/Project-Pandora-Game/pandora/issues/740
- Changed the info/warning/error toasts to be top-left instead of top-right to conflict less with UI elements
- Changed the link color in chats and profiles
- Fixed the incorrect wrapping of long links /words in character and account profiles
> [CHANGE] message toasts location and fixes not working word wrapping in the profiles

- pandora-common/src/gameLogic/assetPreferences/assetPreferencesSubsystemServer.ts
Freezing the data before cleanup obviously causes error when the cleanup would actually try to change something.
This in turn prevented old characters that did have limits set for unknown attributes from loading successfully.
Fixes the following crash:
```
Failed to load character c*** for access ***:
[TypeError: Cannot delete property 'Vagina_protruding' of #<Object>
at CleanupAssetPreferences (/app/node_modules/.pnpm/pandora-common@file+pandora-common/node_modules/pandora-common/src/character/assetPreferences.ts:111:22)
at AssetPreferencesSubsystemServer (/app/node_modules/.pnpm/pandora-common@file+pandora-common/node_modules/pandora-common/src/gameLogic/assetPreferences/assetPreferencesSubsystemServer.ts:25:26)
at GameLogicCharacterServer …
```
> [FIX] Do not freeze asset preferences data before cleanup

- .github/workflows/ci.yml
- package.json
Downgrades pnpm as the latest version is failing with the following errors during docker build, shrinkwrap phase.
Also add a CI to try building docker image to catch this error.
```
 WARN  Failed to create bin at /app/deploy/directory/node_modules/.bin/acorn. ENOENT: no such file or directory, open '/app/deploy/directory/node_modules/.pnpm/acorn@8.11.3/node_modules/acorn/bin/acorn'
 WARN  Failed to create bin at /app/deploy/directory/node_modules/.bin/browserslist. ENOENT: no such file or directory, open '/app/deploy/directory/node_modules/.pnpm/browserslist@4.23.0/node_modules/browserslist/cli.js'
 WARN  Failed to create bin at /app/deploy/directory/node_modules/.bin/ts-node. ENOENT: no such file or directory, open '/app/deploy/directory/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.12 …
```
> [FIX] Downgrade pnpm to 9.0.6 due to failing deployment, add Docker CI

- package.json
Reverts Project-Pandora-Game/pandora#761
The PR was auto-merged because the failing check wasn't set as required. That is now fixed.
> [FIX] Revert "[CHORE] Update pnpm to v9.1.0"

- pandora-client-web/src/assets/assetGraphics.ts
- pandora-client-web/src/assets/graphicsLoader.ts
- pandora-client-web/src/assets/graphicsManager.ts
- pandora-client-web/src/components/settings/helpers/settingsInputs.tsx
- pandora-client-web/src/editor/index.tsx
- pandora-client-web/src/graphics/graphicsLayer.tsx
- pandora-client-web/src/graphics/graphicsScene.tsx
- pandora-client-web/src/graphics/graphicsSettings.tsx
- pandora-client-web/src/graphics/room/roomDevice.tsx
- pandora-client-web/src/graphics/useTexture.ts
- pandora-client-web/src/services/screenResolution/screenResolution.ts
- pandora-client-web/test/setup.ts
**Depends on [pandora-assets#242](https://github.com/Project-Pandora-Game/pandora-assets/pull/242).**
Adds a support for using down-scaled textures.
At the moment resolutions 1 (no change), 1/2, and 1/4 can be selected. This applies to normal assets, room devices and room backgrounds; no matter which screen uses them (both room and wardrobe).
There is also an option for "auto", which tries to guess best resolution automatically (might need tweaking in the future). This is the default.
It works by looking at the true pixel size of the screen (so window size multiplied by DevicePixelRatio (a.k.a. factional scaling). It is tuned such that PC FHD (1080p) screen gets 1/2 resolution (it still looks rather good!), but QHD (1440p) gets full resolution.
For phones the logic works the exact same. …
> [FEATURE] Multiple texture resolutions support

- package.json
- pnpm-lock.yaml
These overrides were added in the past when the dependencies were broken. Both are fixed in the recent versions, so we can remove this extra bit.
> [CHORE] Drop unnecessary dependencies overrides

- pandora-client-web/src/components/settings/accountSettings.tsx
Previously changing display name to above 32 or below 3 wouldn't generate a warning toast. Now it does. 
Fixed by using FormCreateStringValidator similar to registrationForm. 
fixes #743
> [FIX] display name change validates on account settings

- pandora-client-web/src/components/accountContacts/accountContacts.tsx
- pandora-client-web/src/components/directMessages/directMessages.scss
- pandora-client-web/src/components/directMessages/directMessages.tsx
This is a followup to #786, which added scrolling to the current contacts lists.
This PR adds scrolling to the remaining tabs, including fixing scrolling of the open DMs list.
Changelog:
```md
Fixes:
- The remaining tabs in the contacts screen now support scrolling
- Fixed some open Direct Messaging entries possibly being hidden while scrolling
```
> [FIX] Allow scrolling in the remaining Contacts tabs

- pandora-common/src/assets/appearanceActions.ts
- pandora-common/src/character/restrictionTypes.ts
- pandora-common/src/character/restrictionsManager.ts
_None_
This PR changes the restrictions logic of `transfer` and `move` actions so that reordering of items within a single container is not treated as removing and re-adding the item. In this change it allows reordering items even if they cannot be removed.
Reordering locked item with relation to unlocked ones was possible before by simply reordering the unlocked ones freely, so this change only affects relative position of two locked items.
The reasoning behind this change is, that if two locked items shouldn't be reorder-able, there should already be a blocking relationship between them which prevents interactions with the item below. If the two items don't have attribute-based relationship, then they can be treated as separate and can be freely reordered.
Furthermore there is no real …
> [CHANGE] Allow reordering locked items

- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitEditView.tsx
- pandora-client-web/src/components/wardrobe/views/wardrobeOutfitView.tsx
- pandora-common/src/assets/item/_internal.ts
- pandora-common/src/assets/item/base.ts
- pandora-common/src/assets/item/unified.ts
_None_
Items with a custom name are listed within the saved items folder solely with their original asset name. Making it hard to distinguish them, in case of a shoe box, for instance.
This change makes the tab respect the user's settings for custom names instead of just using the name of the asset.
Authored by: Sandrine (with the help of Clare)
```md
- Item templates now save item's name and description
- Makes the saved items tab respect the user's settings for custom names
```
> [CHANGE] Saved items respect custom name settings

- pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemRoomDevice.tsx
_None_
Removes the empty 'Slots' element, if no slots are defined for an asset e.g. the picture frame
Authored by: Sandrine
```md
Fixes:
- Fixed the room devices without a lot still showing empty "Slots" section
```
> [FIX] Avoid empty 'Slots' element

- pandora-client-web/src/components/header/Header.tsx
- pandora-client-web/src/components/header/header.scss
- pandora-client-web/src/styles/_theming.scss
- pandora-client-web/src/ui/screens/room/characterPreviewGeneration.tsx
_None_
n/a
```md
- Made the background of character preview icons transparent for usage of the icon in other parts of Pandora. Note that if you have set some to not automatically update, you may need to update those icons manually to not make them show up with a white background in future usage scenarios.
- Added the character preview icon of the currently active character to the front of the header navigation bar in order to make it easier to identify a browser tab more easily when using multiple characters in parallel. It also doubles as a button to navigate to the wardrobe.
```
> [ADD] character preview in the header bar

- pandora-common/src/gameLogic/characterModifiers/modifierTypes/hearing_selective_deprivation.ts
_None_
Added a new option to the selective hearing modifier:
* Word length
This way long words, that are too complex for some characters can be scrambled with the set intensity.
Authored by: Sandrine
```md
- Added a new configuration option "Words with at most this many letters can always be understood" to the already existing "Hearing: Selective hearing deprivation" character modifier
```
> [ADD] Hearing impediment for long words

- pandora-client-web/src/ui/screens/spacesSearch/spacesSearch.tsx
- pandora-common/src/space/space.ts
- pandora-server-directory/src/spaces/space.ts
Fixes #872 
Added the space's admin list to the publicly available information so that blocked players see who to contact
Authored by: Sandrine
```md
Fixes:
- List of space owners can now be seen even for public spaces you do not have access to
```
> [FIX] Move owner's list to BaseInfo object
